### ISSUE TITLE
Please fix the spelling of hacktoberfest tag on your repository . 

### ISSUE THREAD

**Issue by zetabug** [arpit456jain/Cool-Front-End-Templates#189]
@arpit456jain 
You have written "hactoberfest " instead of "hacktoberfest" in a tag of your repository
Please fix it,or change it , as the label on your repo has to be proper so that it is recognized as "participating " by hacktoberfest .
![Screenshot_20211031-194958_Chrome](https://user-images.githubusercontent.com/72355377/139588239-f545671d-32c1-46a7-9b8a-907d6353e304.jpg)

**Comment by arpit456jain** [comment]
Thanks @zetabug
