### ISSUE TITLE
[ Bug Report] Readme.md 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [arpit456jain/Cool-Front-End-Templates#196]
## Issue Type:

- [YES ] Bug Report

## **Describe the bug**
Hii there , Greeting's of the day
Readme is one of the most important part of the repository which consist of the guidence and flow of conduct . .and if it conatins eroor's then it gave a bad impact ...on organisation

As ur readme conatain's the grammaratical error .. Please asisgn this issue to me so that i can make this correct and grammatical good.
Consider this issue under the ....
GSSOC'22

Thank's and regard's :crossed_fingers:

**Comment by ShrutiKapure** [comment]
I am a GSSOC'22 participant, I want to work on this issue
