### ISSUE TITLE
Blogger's template for gssoc

### ISSUE THREAD

**Issue by Girlwithasmile** [arpit456jain/Cool-Front-End-Templates#198]
Hello, I would like to make and add a blogger's template here. I hope I get this issue assigned!@arpit456jain I am a contributer at gssoc'22 and previously made such templates and clones.

**Comment by Bhawna147** [comment]
Hey, I want to work on this issue under GSSOC'22. Please assign this to me.

**Comment by Girlwithasmile** [comment]
> Hey, I want to work on this issue under GSSOC'22. Please assign this to me.

Hey.... actually I opened this issue cause I wanna work on it.
