### ISSUE TITLE
Add a Responsive Website Template for a Restaurant.

### ISSUE THREAD

**Issue by CoderSahil128** [arpit456jain/Cool-Front-End-Templates#201]
I am a contributor at GSSoC-22. I would like to add a responsive food restaurant template . Please assign this issue to me.
https://user-images.githubusercontent.com/97339865/156048690-7e5690b3-69ca-44e8-b7b5-703bff6f53d0.mp4

**Comment by arpit456jain** [comment]
i think this template is added 

if not create this issue again
