### ISSUE TITLE
Improving Website Navigation Bar

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Cool-Front-End-Templates#202]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

The live page Navbar is set to hide content in mobile devices as shown here
![image](https://user-images.githubusercontent.com/64689436/156076854-36661829-a9d7-4dcc-8b54-dbcb2a81200b.png)
which gives out a bad user experience, as the user have to scroll all the way down to navigate to other website pages.

## **Possible solution**

Making the navbar horizontally scrollable in mobile devices and without showing the scrollbar will result in a better user experience.

**Comment by XZANATOL** [comment]
@arpit456jain can I get assigned for this issue?

**Comment by arpit456jain** [comment]
@XZANATOL someone is already working on it if its not resolved by eod u can create this issue again
