### ISSUE TITLE
Space Agency Website Template

### ISSUE THREAD

**Issue by Rutikab12** [arpit456jain/Cool-Front-End-Templates#203]
## Issue Type:

- [x] Template Code

- I want to add a website template for space agencies like ISRO, NASA, SpaceX. Please assign me this issue under GSSoC'22.

**Comment by Rutikab12** [comment]
Thank you

**Comment by Saba2402** [comment]
Hii there, I wanted to work over this issue but this as well as most of the issues are already assigned.Please assign any of the issue to me.
