### ISSUE TITLE
Hey There ! I want to contribute a landing website for a tours and travels kind of website. Assign me this issue under GSSoC'22

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [arpit456jain/Cool-Front-End-Templates#206]

**Comment by Vedant-Jayesh-Oza** [comment]
Thank for assigning me the issue, currently I am preparing for my college exams which will get over by 9th March, will start working actively after that, Hope you won't mind that 😅

**Comment by astha2412** [comment]
@Vedant-Jayesh-Oza Complete this issue asap, otherwise, I will close this issue or assign it to others.

**Comment by Vedant-Jayesh-Oza** [comment]
I am going to make a PR by the end of the day for sure.

**Comment by Vedant-Jayesh-Oza** [comment]
Sorry for the delay I was going through my exams 😅

**Comment by astha2412** [comment]
> hey @VidhiBhatt01 i am a GSSOC'22 participant and i am working on something similar so is this issue open to contribute ?

Not now.....Make your own issue
