### ISSUE TITLE
Navbar For the Website 

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#207]
## Issue Type:

Create a beautifull responsive navbar for the website and responsiveness too.

**Comment by Abh1shekSingh** [comment]
@arpit456jain  I can work on this issue so please assign this issue to me under GSSOC 2022 . please sir, i can make bauitful navabr and responsive too

**Comment by Abh1shekSingh** [comment]
@arpit456jain  Sir i have developed this beautiful navbar with some changes in color correction according to UI theory
![navbar improvised](https://user-images.githubusercontent.com/71981463/156120903-7a5f4061-0dad-4a28-91d1-98b75b9c88ff.JPG)
![responsive](https://user-images.githubusercontent.com/71981463/156120908-1c351adf-a0b0-467a-b2f3-53b8bf95582b.JPG)

**Comment by Abh1shekSingh** [comment]
SIR PLEASE ASSIGN THIS ISSUE, SO I WILL CREATE PULL REQUEST @arpit456jain

**Comment by anish2210** [comment]
hello @arpit456jain SIR, I want to work on this issue can anyone please assign this work to me I am attaching one of my works with this comment, It is a registration/login page that is built on stackblitz.
MUST CHECK THE RESPONSIVENESS 😊
link - https://angular-ivy-iro2sa.stackblitz.io/

**Comment by Abh1shekSingh** [comment]
> hello @arpit456jain SIR, I want to work on this issue can anyone please assign this work to me I am attaching one of my works with this comment, It is a registration/login page that is built on stackblitz. MUST CHECK THE RESPONSIVENESS 😊 link - https://angular-ivy-iro2sa.stackblitz.io/

Hi bro, I created this issue, and already have worked on it. You kindy find other issue and work on that issue. this issue is not created by  the maintainer. but it is created by me. as according to GSSOC

**Comment by Sanghu01** [comment]
I want to work on this project.

**Comment by arpit456jain** [comment]
its not needed as of now
