### ISSUE TITLE
Homepage UI / UX

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#208]
## Issue Type:

Website is good, But it could be better. UI is not attractive .
Improve the UI / UX design

**Comment by Abh1shekSingh** [comment]
@arpit456jain  SIR PLEASE ASSIGN THIS ISSUE TO ME. I WOULD LOVE WORKING ON THIS ISSUE

**Comment by FatimaBegam** [comment]
Hey there are you participating in GSSoc'22??

**Comment by Abh1shekSingh** [comment]
Yes

**Comment by FatimaBegam** [comment]
Okay

**Comment by Sanghu01** [comment]
I want to work on this project.

**Comment by khushigupta123** [comment]
I am interested in working on this issue, please assign this to me.
