### ISSUE TITLE
Footer for the page || GSSOC'22

### ISSUE THREAD

**Issue by rajaditya28** [arpit456jain/Cool-Front-End-Templates#213]
I would like to take up the task of improving the footer of the site and make a beautiful, interactive and responsive footer.

I am also attaching a footer that I have made on one of my own sites to serve for credibility.

![Screenshot 2022-02-27 201107](https://user-images.githubusercontent.com/68824237/156130677-f4ee35dc-f7fc-4ff4-b14f-d595d6eae79c.png)

Please give suggestions about the type of footer you'd want. 

Could you assign this to me @arpit456jain ? And I will try to improve the look and feel of the footer section and submit a PR as soon as possible.
Thank You !!

**Comment by flow6979** [comment]
hey, can you please assign this to me?
thank you.

**Comment by lavakush07** [comment]
I want to work upon this issue

**Comment by Rishabh-Gaud** [comment]
I am Rishabh Gaud GSSOC'22 participant. I want to solve this issue

**Comment by Rajdip019** [comment]
Hey can I work on this?

**Comment by arpit456jain** [comment]
actually I want a responsive a footer like this if anyone of u can make this do let me know
<img width="953" alt="footer" src="https://user-images.githubusercontent.com/55352601/156188786-b3d1eed0-3d4f-4d07-af9f-c5c242b9c85b.png">

**Comment by Rajdip019** [comment]
Yes sure I can make this! @arpit456jain

**Comment by arpit456jain** [comment]
go ahead @Rishabh-Gaud

**Comment by trDalmi** [comment]
Hi there, if this issue is not resolved yet can u assign it to me under the GSSOC22 tag.
