### ISSUE TITLE
Add My New Year Countdown Timer Project

### ISSUE THREAD

**Issue by Susmita-Dey** [arpit456jain/Cool-Front-End-Templates#215]
## Issue Type: Hey admin! I want to add my New Year Countdown Timer Project to your site , I am contributor at GSSoC'22. Please assign this issue to me.

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**
I want to add this here.
**It's animated and responsive too.**
- Repository Link:- https://github.com/Susmita-Dey/Happy-New-Year-CountDown-Timer-Project
- Live demo:- https://susmita-dey.github.io/Happy-New-Year-CountDown-Timer-Project/

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/79099734/156151809-16fa3a76-c317-4f93-bfce-ca50d0ab8f0d.png)

**Comment by arpit456jain** [comment]
https://github.com/arpit456jain/Amazing-Js-Projects

**Comment by Susmita-Dey** [comment]
Ok, I'm creating an issue there.
