### ISSUE TITLE
Add My Password Generator Project

### ISSUE THREAD

**Issue by Susmita-Dey** [arpit456jain/Cool-Front-End-Templates#216]
## Issue Type: Hey admin! I want to add a Password Generator to your site. I am contributor at GSSoC'22. Please assign this issue to me.

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**
I want to add this here.

- Repository Link:- https://github.com/Susmita-Dey/Password-Generator
- Live demo:- https://susmita-dey.github.io/Password-Generator/

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/79099734/156152396-d586d3d2-c269-4f38-bbf3-86ba7649851c.png)

**Comment by arpit456jain** [comment]
create on issue on  https://github.com/arpit456jain/Amazing-Js-Projects

**Comment by Susmita-Dey** [comment]
> create on issue on https://github.com/arpit456jain/Amazing-Js-Projects

Okay, creating.
