### ISSUE TITLE
Adding Parallex Website Design using Html Css & Scroll Trigger

### ISSUE THREAD

**Issue by Nanshi29** [arpit456jain/Cool-Front-End-Templates#218]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation

**Comment by soumali28** [comment]
I want to work on this issue under Gssoc

**Comment by arpit456jain** [comment]
create a issue on https://github.com/arpit456jain/Amazing-Css-Effects
