### ISSUE TITLE
Animated Glassmorphism Card Design

### ISSUE THREAD

**Issue by Gaurika-Gupta** [arpit456jain/Cool-Front-End-Templates#219]
Frontend Design using HTML and CSS

**Comment by Gaurika-Gupta** [comment]
Please add GSSOC'22 tag and assign me the issue
Thank you

**Comment by Debdeep1** [comment]
I want to work on this issue under GSSoC'22

**Comment by Rajdip019** [comment]
I would love to work on this. Ca you assign me this?
