### ISSUE TITLE
Want to add memory game

### ISSUE THREAD

**Issue by soumali28** [arpit456jain/Cool-Front-End-Templates#221]
## Issue Type:

- [x] Feature Request

## **Describe the bug**
This is not a bug. I want to add a memory game.

## **Possible solution**

The memory game will be build using html, css and js.

## **Screenshots**

![Memory Game - Google Chrome 3_1_2022 6_22_49 PM](https://user-images.githubusercontent.com/66300439/156172356-82a779f6-101e-4536-b533-f121e4f7eb43.png)

**Comment by debjitpurohit** [comment]
I want to add a memory game .assign this to me

**Comment by arpit456jain** [comment]
@soumali28 create this issue on https://github.com/arpit456jain/Amazing-Js-Projects

**Comment by soumali28** [comment]
Ok
