### ISSUE TITLE
A business/project template

### ISSUE THREAD

**Issue by 1ananya3** [arpit456jain/Cool-Front-End-Templates#225]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- A business/project template where someone can use to make their website.

## **Possible solution**

- We give them amazing layout styles, theme options and many more.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by 1ananya3** [comment]
@arpit456jain Please assign me in this issue. I can make it.

**Comment by astha2412** [comment]
@1ananya3 Complete this issue asap, otherwise, I will close this issue or assign it to others.
