### ISSUE TITLE
Spotify Clone

### ISSUE THREAD

**Issue by 1ananya3** [arpit456jain/Cool-Front-End-Templates#227]

**Comment by astha2412** [comment]
@1ananya3 Complete this issue asap, otherwise, I will close this issue or assign it to @ShrutiKapure.

**Comment by VidhiBhatt01** [comment]
@ShrutiKapure are you willing to work on this?

**Comment by ShrutiKapure** [comment]
> @ShrutiKapure are you willing to work on this?

Yes.

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
