### ISSUE TITLE
Navbar design fix

### ISSUE THREAD

**Issue by YalfamIamShaon** [arpit456jain/Cool-Front-End-Templates#228]
## Issue Type:
Fixing the design of the Navbar 

## **Describe the bug**

- I want fix the design of the Navbar and make it more attractive

**Comment by YalfamIamShaon** [comment]
I have made few websites, and I can design the Navbar and make it look more interactive. As a GSSOC 22 participant I want to work on this, please assign it to me.

**Comment by astha2412** [comment]
> I have made few websites, and I can design the Navbar and make it look more interactive. As a GSSOC 22 participant I want to work on this, please assign it to me.

you have to make full template.....not only navbar

**Comment by arpit456jain** [comment]
> I have made few websites, and I can design the Navbar and make it look more interactive. As a GSSOC 22 participant I want to work on this, please assign it to me.

as of now there is no need 

@YalfamIamShaon u can your templates here and in https://github.com/arpit456jain/Amazing-Css-Effects
