### ISSUE TITLE
Add a LinkedIn clone to this repo

### ISSUE THREAD

**Issue by pratham-ops** [arpit456jain/Cool-Front-End-Templates#230]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by B1TSH3LL** [comment]
hello , i would like to work on this issue can you just assign it to me 💯

**Comment by pratham-ops** [comment]
> hello , i would like to work on this issue can you just assign it to me 💯

You can start working on it @B1TSH3LL

**Comment by astha2412** [comment]
@pratham-ops Complete this issue asap, otherwise, I will close this issue or assign it to others.

**Comment by VidhiBhatt01** [comment]
@B1TSH3LL are you willing to work on this?
