### ISSUE TITLE
Template for Weather forecast

### ISSUE THREAD

**Issue by vardhinii** [arpit456jain/Cool-Front-End-Templates#231]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- It contains no bug. Suggestion for adding a template.

## **Possible solution**

- Create new or replace the existing weather page template with a new template with modern UI made with HTML and CSS.
- I'm participating in GSSOC'22 and I will make this feature.

# **Screenshots**

- Suggested UI template to be added not exactly the same.

![images (6)](https://user-images.githubusercontent.com/77223276/156215993-4bf1f126-5440-476a-8f64-b64a1e8d52bf.jpeg)

**Comment by arpit456jain** [comment]
crearte this issue on https://github.com/arpit456jain/Amazing-Js-Projects
