### ISSUE TITLE
Glassmorphism weather  Widget UI Design

### ISSUE THREAD

**Issue by CoderSahil128** [arpit456jain/Cool-Front-End-Templates#233]
I am a contributor from GSSoC - 22. I can create different kinds of glassmorphism card UI designs like glowing gradients and etc. and can add some effects like hover and tilt effects.so Please assign this issue to me. Here are some of my works.
![Demo 1](https://user-images.githubusercontent.com/97339865/156224144-bfb280a8-81c5-47ef-a2bc-0fd41ed7a310.jpeg)

**Comment by TG922** [comment]
Hey! @arpit456jain I would like to work on this issue under GSSoC'22 . Please Assign me with this issue .

**Comment by sulogna2001** [comment]
Hey Can I work  on  this issue under GSSOC22

**Comment by VidhiBhatt01** [comment]
Issue assigned to you @CoderSahil128. Happy contributing!

**Comment by CoderSahil128** [comment]
> Issue assigned to you @CoderSahil128. Happy contributing!

Thank you 👍
