### ISSUE TITLE
UI enhancement for Weather template

### ISSUE THREAD

**Issue by AjeetSingh2016** [arpit456jain/Cool-Front-End-Templates#236]
## Issue Type:

Feature Request

#### - Please assign me on this under **GSSoC22**.

![gssoc ss](https://user-images.githubusercontent.com/80536741/156240981-d1b1016e-dfa2-432b-b4eb-15199de7fe64.png)

**Comment by VidhiBhatt01** [comment]
Issue assigned to you @AjeetSingh2016 . Happy contributing!
