### ISSUE TITLE
Resume Template

### ISSUE THREAD

**Issue by 1ananya3** [arpit456jain/Cool-Front-End-Templates#237]
A resume building template , simple and clean site.

**Comment by 1ananya3** [comment]
Assign me in this issue.

**Comment by adityabhatia17** [comment]
I have made a resume template. Please assign me this issue.

**Comment by VidhiBhatt01** [comment]
@1ananya3 issue assigned to you.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by astha2412** [comment]
@1ananya3 you have already made 2-3 issues and haven't completed a single one, so I m assigning this issue to @adityabhatia17. Complete it asap!

**Comment by 1ananya3** [comment]
My mid semester exam has started.That's why I cant manage to do my
task.Give me 5days i'll complete it asap.Thank you .

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
