### ISSUE TITLE
move pic of hactoberfest to below devincept and replace it with the logo og GSSoC'22

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#239]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
create this issue in other 2 projects as well

**Comment by sarthakk24** [comment]
i would like to work on this issue can you assign it to me .
