### ISSUE TITLE
using some best attributes and tags

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [arpit456jain/Cool-Front-End-Templates#240]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Khushbu-kumari-87090** [comment]
heyy@arpit please  assign me.

**Comment by VidhiBhatt01** [comment]
> ## Issue Type:
> * [ ]  Bug Report
> * [ ]  Feature Request
> * [ ]  Documentaion
> 
> ## **Describe the bug**
> * A clear and concise description of what the bug is.
> 
> ## **Possible solution**
> * Describe the solution you thought of.
> 
> ## **Screenshots**
> * If applicable, add screenshots to help explain your problem.

@Khushbu-kumari-87090 please fill this template properly.

**Comment by Khushbu-kumari-87090** [comment]
can i add the some fresh nature image with  motivational quotes

**Comment by VidhiBhatt01** [comment]
> can i add the some fresh nature image with motivational quotes

yes

**Comment by Khushbu-kumari-87090** [comment]
thanks but if are assigned to me this project  so  i  feel so comfotable . so please assign me.

**Comment by VidhiBhatt01** [comment]
Fill the template first

**Comment by VidhiBhatt01** [comment]
I will assign it you after that
