### ISSUE TITLE
Wrong Preview for Apple Website Ui clone

### ISSUE THREAD

**Issue by Girlwithasmile** [arpit456jain/Cool-Front-End-Templates#241]
The preview given on main page for apple website ui clone is wrong. I would like to work on this under gssoc'22.
![wrong apple clone preview](https://user-images.githubusercontent.com/98261167/156291806-27deef3e-88b3-47fb-80a2-9ad72f47bb49.png)

**Comment by VidhiBhatt01** [comment]
> The preview given on main page for apple website ui clone is wrong. I would like to work on this under gssoc'22. ![wrong apple clone preview](https://user-images.githubusercontent.com/98261167/156291806-27deef3e-88b3-47fb-80a2-9ad72f47bb49.png)

Sure!
