### ISSUE TITLE
Brick-Breaker

### ISSUE THREAD

**Issue by sirilalithaadapa** [arpit456jain/Cool-Front-End-Templates#242]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- It's a cool front end game in which we break the brick

## **Vedio**

https://user-images.githubusercontent.com/70501362/156304700-87675a13-bdf6-40c8-8c81-3d725ff80308.mp4

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
@sirilalithaadapa raise this issue in amazing js projects repo.

**Comment by sirilalithaadapa** [comment]
ok
