### ISSUE TITLE
Hello, I would like to add beautiful footer for this website. Please allow me to work on this issue for GSSOC22

### ISSUE THREAD

**Issue by Siddhi-Mundada** [arpit456jain/Cool-Front-End-Templates#245]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Footer is must for any website where social media links and logo and name of website and some useful can be added that's why I raised this issue.

## **Possible solution**

- I would like to create a beautiful and attractive footer using Html, CSS and will also add hyperlinks.

**Comment by AnIkeT126** [comment]
Can I work on this issue too @arpit456jain as a part of GSSoC'22?

**Comment by VidhiBhatt01** [comment]
@Siddhi-Mundada please fill the issue template properly.

**Comment by VidhiBhatt01** [comment]
> ## Issue Type:
> * [ ]  Bug Report
> * [ ]  Feature Request
> * [ ]  Documentaion
> 
> ## **Describe the bug**
> * A clear and concise description of what the bug is.
> 
> ## **Possible solution**
> * Describe the solution you thought of.
> 
> ## **Screenshots**
> * If applicable, add screenshots to help explain your problem.

This is the template.

**Comment by RajatBhaskare7** [comment]
can you assign me this task
