### ISSUE TITLE
Add WhatsApp Web template

### ISSUE THREAD

**Issue by Avik-creator** [arpit456jain/Cool-Front-End-Templates#247]
## Feature Request / Template Issue

# Want to add WhatsApp Web Template

I want to add WhatsApp Web template. My name is Avik Mukherjee GSSOC 2022 contributer.

**Comment by VidhiBhatt01** [comment]
> ## Feature Request / Template Issue
> # Want to add WhatsApp Web Template
> I want to add WhatsApp Web template. My name is Avik Mukherjee GSSOC 2022 contributer.

Sure!

**Comment by Avik-creator** [comment]
Ok I will start working today.
