### ISSUE TITLE
Image slider with multiple controls and mobile swipe control (Javascript)

### ISSUE THREAD

**Issue by SayedTabish72** [arpit456jain/Cool-Front-End-Templates#248]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [X] Documentaion

## Description

- Image slider with multiple controls and mobile swipe control (Javascript) is created by  using **HTML, CSS, Javascript** . Image slider with multiple controls and mobile swipe control **(Javascript)**.  Image slider with multiple controls and mobile swipe control (Javascript) example is best for Bootstrap responsive. It is very easy to add snippets to your project and easy to modify.

## **Screenshots**
https://user-images.githubusercontent.com/93794214/156314935-688bc2bb-f91c-45fd-a3fc-8805a050b5d2.mp4
- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
@SayedTabish72 raise this issue in the amazing js projects repo. I will assign it to you.
