### ISSUE TITLE
I would like  to add a beautiful responsive eLaundry website template under GSSOC'22

### ISSUE THREAD

**Issue by ANJALI-KUKRETI** [arpit456jain/Cool-Front-End-Templates#249]
## Issue Type:

- [ ] Feature Request

## **Describe the bug**

Want to add a new template

## **Possible solution**
https://user-images.githubusercontent.com/89701349/156317378-8ff31574-87a1-41d3-b9d2-21dd86f2cd7e.mp4

**Comment by arpit456jain** [comment]
@ANJALI-KUKRETI make PR asap

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
