### ISSUE TITLE
Add a Carousel Landing page template

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Cool-Front-End-Templates#251]
## Issue Type:

- [x] Feature Request

## **idea**

Add a carousel landing page template that is suitable for volunteering comunities to present themselves in a compact modern way. 

## **Screenshots**

This is a demo of an already established website. (Images are blurred)

![image](https://user-images.githubusercontent.com/64689436/156337695-9f63bf89-980a-4994-9669-2a139b0983f3.png)

![image](https://user-images.githubusercontent.com/64689436/156338010-449de79b-ca50-4154-b8e7-331b08d3b2ac.png)

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
