### ISSUE TITLE
Add the new  webpages regarding valuable quotes

### ISSUE THREAD

**Issue by Smriti-y** [arpit456jain/Cool-Front-End-Templates#255]
I would like to add some valuable quotes of great personalities all over the worlds and several life lessons(some of the incidents and experiences being shared by them, ex- A P J Abdul kalam sir) that may motivate the user.

**Comment by VidhiBhatt01** [comment]
> I would like to add some valuable quotes of great personalities all over the worlds and several life lessons(some of the incidents and experiences being shared by them, ex- A P J Abdul kalam sir) that may motivate the user.

Sure!

**Comment by Smriti-y** [comment]
Sir , Is there any discord channel for this project too.

**Comment by VidhiBhatt01** [comment]
yes

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by VidhiBhatt01** [comment]
Issues are assigned on an FCFS basis. You can check out other issues @sceary-expert

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready

**Comment by Smriti-y** [comment]
Sir, I have to raise new issue????

**Comment by Smriti-y** [comment]
Sir I have reopened the issue today but it's showing failed and something like ---"issue labeler"
