### ISSUE TITLE
To Add a Interior Home design template

### ISSUE THREAD

**Issue by yashikhare** [arpit456jain/Cool-Front-End-Templates#260]
I want to add A project template where someone can use to make their website.
With help of Html and css I am going to make this template.
I'm contributor in GSSOC22, can you please assign this issue to me?

**Comment by VidhiBhatt01** [comment]
> I want to add A project template where someone can use to make their website. With help of Html and css I am going to make this template. I'm contributor in GSSOC22, can you please assign this issue to me?

Hey @yashikhare please elaborate a little more, like what all will you include ?

**Comment by yashikhare** [comment]
I want to add a web page of interior home design.
This will be a responsive webpage of interior home design.
I will use Html and css for making this template

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by yashikhare** [comment]
hi, just give me one more day I am gonna upload my project.
