### ISSUE TITLE
Add a restaurant website template

### ISSUE THREAD

**Issue by kheya19** [arpit456jain/Cool-Front-End-Templates#262]
I can make a responsive restaurant website template

**Comment by bhavyapathak20** [comment]
Hello! I would like to make a responsive restaurant template. 
I will be using the following languages to build the website:
1) **HTML**
2)**CSS**
3)**Bootstrap**
4)**Javascript**
5)**Jquery**

Kindly assign this task to me.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
