### ISSUE TITLE
Adding a landing page template 

### ISSUE THREAD

**Issue by Sandhya312** [arpit456jain/Cool-Front-End-Templates#263]
**I am a GSSOC'22 contributor**
I want to add an awesome landing page template to your project.

**Comment by VidhiBhatt01** [comment]
> **I am a GSSOC'22 contributor** I want to add an awesome landing page template to your project.

Go on!

**Comment by Sandhya312** [comment]
> > **I am a GSSOC'22 contributor** I want to add an awesome landing page template to your project.
> 
> Go on!

Thank you for assigning me.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by dvlsatya** [comment]
i would like to work on this issue

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
