### ISSUE TITLE
Add photo gallery website

### ISSUE THREAD

**Issue by AnishaRoy1** [arpit456jain/Cool-Front-End-Templates#264]
I want to add a photo gallery website.

**Comment by arpit456jain** [comment]
did u create this issue in any other of our repo ?

**Comment by AnishaRoy1** [comment]
Yes I have created this issue in the Amazing JS project but you asked me to
create this in this "cool front end template" and you closed that issue in
the other repo. Thank you.

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.
