### ISSUE TITLE
Portfolio Template

### ISSUE THREAD

**Issue by dexterousb** [arpit456jain/Cool-Front-End-Templates#267]
A very elegant and impressive UI Design.

**Comment by Shobhit61730** [comment]
Can you assign this issue to me?

**Comment by sceary-expert** [comment]
DHANANJOY DEY | Contributor#7903. I want to work on this under GSSOC2022.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
