### ISSUE TITLE
fashion shopping front-end webpage 

### ISSUE THREAD

**Issue by shubhra-g** [arpit456jain/Cool-Front-End-Templates#280]
An interactive front-end template for a shopping website.

**Comment by shubhra-g** [comment]
@arpit456jain  can you assign me to this issue?

**Comment by ShrutiKapure** [comment]
I have already created an E-commerce-shopping website using HTML, CSS, JavaScript. The website contains shopping cart, about, login/signup etc.
I want to contribute on this issue under GSSOC'22.

**Comment by sophiastr** [comment]
Hello, can you assign me to this issue?
Thank you

**Comment by VidhiBhatt01** [comment]
Assigned it to you @sophiastr

**Comment by DEEPIKA-SUK** [comment]
@sophiastr any update? Make PR otherwise we will close this issue.
