### ISSUE TITLE
want to make Responsive the Food template and add some effect on button 

### ISSUE THREAD

**Issue by Princykri** [arpit456jain/Cool-Front-End-Templates#284]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**
Its is not Responsive

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (111)](https://user-images.githubusercontent.com/91013588/156511684-e530c401-e77f-42b4-94de-a6d8a5ca6040.png)

**Comment by Naresh-chandanbatve** [comment]
hey I would like to work on this.
please assign it to me it no one is working on it.

**Comment by Princykri** [comment]
@Naresh-chandanbatve  _Sorry to say but I have created this issue.

**Comment by Naresh-chandanbatve** [comment]
> @Naresh-chandanbatve _Sorry to say but I have created this issue.

Ohk no worries..

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
