### ISSUE TITLE
Add favicon to website 

### ISSUE THREAD

**Issue by khushigupta123** [arpit456jain/Cool-Front-End-Templates#287]
## Issue Type:

Feature Request

## **Description**

- I want to design and add a favicon to the website as currently it is not there.

##**Importance of favicon** 

- Make website attractive
- Provide individuality to the website
- Make it easier for users to find website tab among other tabs

**I am a GSSOC 2022 participant,
Kindly assign this issue to me.**

**Comment by suman-shah** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
