### ISSUE TITLE
want to make Responsive Money Lone Website template with smtp email services forms

### ISSUE THREAD

**Issue by adi2002vicky** [arpit456jain/Cool-Front-End-Templates#288]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![Screenshot 2022-03-03 151304](https://user-images.githubusercontent.com/78430607/156539017-f1172450-7336-4646-8adc-1addf8216bda.png)

- If applicable, add screenshots to help explain your problem.

**Comment by adi2002vicky** [comment]
hii i am gssoc2022 contributor pls assign me sir pls check pr i have already done my works
![Screenshot 2022-03-03 153528](https://user-images.githubusercontent.com/78430607/156543442-df1a1011-1552-453f-8b07-a53d6b3cf970.png)
![Screenshot 2022-03-03 153553](https://user-images.githubusercontent.com/78430607/156543455-9123cef6-4d9e-4222-a4a8-a61fb8670780.png)

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
