### ISSUE TITLE
Website Template for Bootcamp

### ISSUE THREAD

**Issue by Rutikab12** [arpit456jain/Cool-Front-End-Templates#295]
## Issue Type:

- [x] Feature Request

## **Describe**

- A ready-to-use website template for BootCamp made with pure bootstrap. It will be useful to change the content and use for any type of Bootcamp.

- Please assign me this issue as a GSSoC'22 participant.
- Below are the demo images of a template designed for, for example, web development BootCamp 

![ss1](https://user-images.githubusercontent.com/71027989/156605154-a6f8a6e1-fa66-4381-8b22-d225e4eadda5.jpg)

![ss2](https://user-images.githubusercontent.com/71027989/156605336-9ecf489d-6fc4-4641-9b5b-00dbbf227f6d.jpg)

**Comment by astha2412** [comment]
Add ss or video!
