### ISSUE TITLE
College  frontEnd webpage 

### ISSUE THREAD

**Issue by Ankitsingh2001** [arpit456jain/Cool-Front-End-Templates#296]
**I want a chance to make an amazing animated web page for college**

So please  sir assign me

**Comment by astha2412** [comment]
Add ss or video

**Comment by bhavyapathak20** [comment]
I would like to contribute in this issue

**Comment by bhavyapathak20** [comment]
Hello! I would like to make a responsive college website. 
I will be using the following languages to build the website:

1) **HTML**
2)**CSS**
3)**Bootstrap**
4)**Javascript**
5)**Jquery**

Kindly assign this task to me.

**Comment by Ankitsingh2001** [comment]
ok sure

**Comment by Ankitsingh2001** [comment]
![Screenshot (198)](https://user-images.githubusercontent.com/89564535/156719491-149055f1-b873-4470-9e41-1cd80d605d37.png)
