### ISSUE TITLE
I want to add  a landing page website got video calling

### ISSUE THREAD

**Issue by soumali28** [arpit456jain/Cool-Front-End-Templates#299]
## Issue Type:

- [ ] Feature Request

## **Describe the bug**

- This is feature which I want to add as a landing page. It will be created using HTMl , CSs and bootstrap.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
Add SS or video

**Comment by soumali28** [comment]
This is the website I want to add.
https://user-images.githubusercontent.com/66300439/156708448-3cb2e459-3ec3-449b-9972-840d6c0be7d6.mp4

**Comment by mayank-del** [comment]
Can you elaborate?
means , that page will have  animated phone  which will oscillate up and down, right?

**Comment by soumali28** [comment]
No its just a basic landing page just the design done in html and css.
