### ISSUE TITLE
Contest Page

### ISSUE THREAD

**Issue by sirilalithaadapa** [arpit456jain/Cool-Front-End-Templates#301]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Contest Page like photography, art, singing contest

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

![Screenshot (122)](https://user-images.githubusercontent.com/70501362/156598685-3ee67f93-ee00-465e-81ed-eb1fdf2eaca7.png)
![Screenshot (123)](https://user-images.githubusercontent.com/70501362/156598762-b287497c-c4b1-41bb-abd9-8634f12a4d31.png)

**Comment by sirilalithaadapa** [comment]
> Hello, Can you assign this issue to me?

nope i completed working on it

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by sirilalithaadapa** [comment]
> I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

It is already assigned to me and also completed working onit!

And submitted a pull request to

**Comment by VidhiBhatt01** [comment]
Is it completed? If not, reopen this issue when PR is ready
