### ISSUE TITLE
Fix section 12 on Chinese Restaurant template

### ISSUE THREAD

**Issue by yasledesma** [arpit456jain/Cool-Front-End-Templates#308]
Hello, I would like to take on this issue as a GsSoC contributor

## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- The social media list on this section is offset to left instead of being centered, both on desktop and mobile.
- When the user hovers over an icon, they grow in size, but they also cause the the container to grow.

## **Screenshots**

![Screenshot](https://i.imgur.com/mbXM7SV.png)

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.
