### ISSUE TITLE
I want To Add Vegetable  website tamplate

### ISSUE THREAD

**Issue by adi2002vicky** [arpit456jain/Cool-Front-End-Templates#309]
## Issue Type:

- [x] Feature Request
![Screenshot 2022-03-04 100156](https://user-images.githubusercontent.com/78430607/156699971-e24c9ba0-7d83-4f50-9719-54fe906eadd4.png)

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by adi2002vicky** [comment]
please assign me and check pr sir

**Comment by astha2412** [comment]
@adi2002vicky Make a new issue when u r ready!
