### ISSUE TITLE
Add New CSS effect template!

### ISSUE THREAD

**Issue by manni2000** [arpit456jain/Cool-Front-End-Templates#311]
Hello PM Sir, I'm a Manish Kumar contributor of GSsoc'22.
Sir, I wanted to add like Intro video 'Welcome CSS Effect template' in the Amazing-CSS-Effects section. 
So please give me an issue.
Thank you.

**Comment by VidhiBhatt01** [comment]
@manni2000 raise this issue in amazing CSS effects repo
