### ISSUE TITLE
Youtube Clone

### ISSUE THREAD

**Issue by vardhinii** [arpit456jain/Cool-Front-End-Templates#313]
## Issue Type:
Adding a YouTube dashboard clone to the list of projects, made using HTML, CSS, Javascript.

- [x] Feature Request

## **Possible solution**

+ Responsive Webpage that supports all devices.
+ Youtube Clone

## **Screenshots**
![Screenshot_20220304-124732_Chrome](https://user-images.githubusercontent.com/77223276/156717362-8281156f-77db-44a5-8acb-11cbe860391c.jpg)

**Comment by astha2412** [comment]
@vardhinii Make a new issue when u r ready!
