### ISSUE TITLE
App Launch Template

### ISSUE THREAD

**Issue by Rashmisingh-18** [arpit456jain/Cool-Front-End-Templates#315]
App Launch Template that inlcude-Why to buy/download that app, features of the app, what features include for free purchase and its premium purchase.

**Comment by Rashmisingh-18** [comment]
Please assign this issue to me @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
@Rashmisingh-18 can you assign some SS or video?

**Comment by Rashmisingh-18** [comment]
The video is attached:

https://user-images.githubusercontent.com/90052358/156785926-26eca678-919e-4539-8e57-ee858e35a88a.mp4

**Comment by Rashmisingh-18** [comment]
Please check that video and please assign this to me @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
Assigned, sorry for the delay. I somehow missed the message
