### ISSUE TITLE
Technology Font End

### ISSUE THREAD

**Issue by Abhishek2408** [arpit456jain/Cool-Front-End-Templates#316]
## **Possible solution**

- A website look very simple and whitish .i want to make changes in header and footer section like add navigation bar to navigate through whole website and add some animation and color contrast etc.

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by Abhishek2408** [comment]
I have done it and also raise the pull request please assign role to me under gssoc'22

**Comment by VidhiBhatt01** [comment]
@Abhishek2408 please elaborate more on what will you include?

**Comment by Abhishek2408** [comment]
@VidhiBhatt01 Navigation bar as it looks simple i have added color contrast in it. i have made some changes in CEO section the images is now properly aligned as u can see in images.
In below images u can see the enhancement  which i have done.
![image](https://user-images.githubusercontent.com/87486132/156774194-e3f5459f-18e8-49cf-9077-0b01bc05d3d8.png)
![image](https://user-images.githubusercontent.com/87486132/156774226-1e39088b-94bc-453f-a9c4-43625f6ca510.png)
![image](https://user-images.githubusercontent.com/87486132/156774260-1e31c90a-efae-4e0a-8003-e35d24931176.png)

**Comment by Abhishek2408** [comment]
@VidhiBhatt01 can u please merge the request which i have pulled.

**Comment by arpit456jain** [comment]
its invalid make another PR but make sure u r not destroying its responsiveness

**Comment by Abhishek2408** [comment]
@arpit456jain  Ya Ya Sorry for that i haven't seen that

**Comment by Abhishek2408** [comment]
@arpit456jain @VidhiBhatt01 Can u please check and merge pull request.

**Comment by Abhishek2408** [comment]
@arpit456jain nothing pr is already merged.Thanks
