### ISSUE TITLE
Add footer in "COOL FRONT END TEMPLATES" 

### ISSUE THREAD

**Issue by SachinMittal1766** [arpit456jain/Cool-Front-End-Templates#319]
## Issue Type:
- [ ] Feature Request

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.
- I will add a footer which will contain contact info, copyright etc.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
@SachinMittal1766 Can you attach a SS or video of the footer?

**Comment by arpit456jain** [comment]
@SachinMittal1766 some is working on it currently no need of this issue
