### ISSUE TITLE
Add a product landing page for a hands-free speaker

### ISSUE THREAD

**Issue by varisha-025** [arpit456jain/Cool-Front-End-Templates#322]
## Issue Type:

- [x] Feature Request

I want to add a product landing page for a hands-free speaker. It has animations and great hover effects.
I just have to make it mobile responsive and do some adjustments. If you like it, assign me the issue. 

## **Screenshots**

<img width="1436" alt="Screenshot 2022-03-04 at 7 13 02 PM" src="https://user-images.githubusercontent.com/81171573/156774272-d30e8377-7fac-49fe-b4ca-4ee0c27fc08b.png">

<img width="1433" alt="Screenshot 2022-03-04 at 7 13 40 PM" src="https://user-images.githubusercontent.com/81171573/156774282-c5fc1b12-799c-4baf-a71f-f97dbd6cadd0.png">

<img width="1433" alt="Screenshot 2022-03-04 at 7 13 59 PM" src="https://user-images.githubusercontent.com/81171573/156774289-1245e735-3362-4e20-baa9-8d397c5e7185.png">

<img width="1440" alt="Screenshot 2022-03-04 at 7 14 25 PM" src="https://user-images.githubusercontent.com/81171573/156774297-401c7999-4201-4099-8c55-880f97e8b3ec.png">

**Comment by astha2412** [comment]
@varisha-025 Make issue again....when u r ready!
