### ISSUE TITLE
Update Navber links hover effect.

### ISSUE THREAD

**Issue by Aritra777** [arpit456jain/Cool-Front-End-Templates#326]
I want to make navbar links hover effect like the following website previously done by me.
## **Screenshots**
![Screenshot (34)](https://user-images.githubusercontent.com/93366359/156785503-b022b9dc-b20e-4403-b9ad-537c70e1d204.png)

Please assign me @arpit456jain under GSSOC'22.

**Comment by VidhiBhatt01** [comment]
@Aritra777 you can add a new folder and make a navbar whichever way you like but kindly do not change the layout of main website.
