### ISSUE TITLE
Add Payment-Page with HTML, CSS and JS

### ISSUE THREAD

**Issue by darkhorse-2000** [arpit456jain/Cool-Front-End-Templates#327]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Description**

- A payment page using frontend.

## **Stacks Used**

- HTML
- CSS
- Javascript

I am a GSSOC'22 Contributor. Please assign this issue to me.

**Comment by Khushi25pandey** [comment]
I would like to work on the issue. Please assign it to me.
