### ISSUE TITLE
Add: Subscribe Newsletters Template

### ISSUE THREAD

**Issue by AjeetSingh2016** [arpit456jain/Cool-Front-End-Templates#332]
## Issue Type:

Feature Request

## **Describe the bug**

- Right now there is no template for **Subscribe Newsletters**

## **Possible solution**

- I want to add **Subscribe Newsletters** template

### Please assign me on this issue under **GSSoC22**

**Comment by suman-shah** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
