### ISSUE TITLE
Creating a yoga website template

### ISSUE THREAD

**Issue by NikitaTalreja** [arpit456jain/Cool-Front-End-Templates#334]
Hi,
I would like to design the Yoga template. 

2. Following things can be added to the template
a.introductory section consisting of navbar
b. the testimonial section 
c. benefits of yoga section
d. section indicating different classes schedules, timings, duration
e. section indicating the numbers like number of lives impacted, number of teachers in yoga class and so on
f.  gallery section

If you want I can provide you with a mock-up in a few days and after finalizing it, I can start working on it

**Comment by Cypher1002** [comment]
hey i am interested in resolving this issue 
what will be  the deadline of this issue

**Comment by ShrutiKapure** [comment]
I want to work on this issue under GSSOC'22.

**Comment by arpit456jain** [comment]
@NikitaTalreja make PR other wise it will be assigned to other person

**Comment by VidhiBhatt01** [comment]
Assigned the issue  to you @Cypher1002

**Comment by Cypher1002** [comment]
Thanks for assigning it to me

**Comment by arpit456jain** [comment]
@Cypher1002 instead of adding new yoga template u can improve the any of the two existing ones
https://cool-front-end-templates.netlify.app/yoga%20template/
https://cool-front-end-templates.netlify.app/yoga%20template%202/

create  a new issue for it

**Comment by Cypher1002** [comment]
Okay
