### ISSUE TITLE
Improve the chinese restaurant template 

### ISSUE THREAD

**Issue by maura-dev** [arpit456jain/Cool-Front-End-Templates#338]
## **Describe the bug**

-The template is not mobile responsive. 
-There is also a x-axis overflow on both mobile and desktop view
- The sections are not stacked properly w
- The nav-bar has very large font 
- The entire template has bad user experience

## **Possible solution**

- I intend to properly arrange the sections
- Work on the responsiveness and user experience by adding some effects and animations on the page

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Pranjali-49** [comment]
Hey , @maura-dev I'm working under GSSOC'22 .  I would like work on this issue , can you please assign this to me?

**Comment by Pratiksha-Daphal** [comment]
Hey , @maura-dev I'm working under GSSOC'22 . I would like work on this issue , can you please assign this to me?
