### ISSUE TITLE
Background Image Slider

### ISSUE THREAD

**Issue by ankudubey28** [arpit456jain/Cool-Front-End-Templates#344]
**Background Image slider**
     PROJECT DESCRIPTION 
1 - A default image should be displayed when we load the 
     page.
2 - when we click the "Left button" one of the five image 
     should display, all the way until each of the five 
       numbers display in sequence.
3 - Repeat step 2 for "Right button".

**Comment by Sanghu01** [comment]
i want to contribute in this issue under gsscoc'22.

**Comment by Apexshya** [comment]
I am GSSoC participant and I would like to work on this issue.
