### ISSUE TITLE
PortFolio Animated Template

### ISSUE THREAD

**Issue by bhumikatewary** [arpit456jain/Cool-Front-End-Templates#347]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Describe the bug**

- No bugs present

## **Possible solution**

- This is an animated portfolio template 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot (55)](https://user-images.githubusercontent.com/77784592/156911933-594190c4-3a9e-49d9-8ee9-264ec47ae79e.png)
![Screenshot (56)](https://user-images.githubusercontent.com/77784592/156911955-5e7a4b3f-e2fe-4930-9fd1-68160e2d2ba6.png)
![Screenshot (57)](https://user-images.githubusercontent.com/77784592/156911975-1d6469e5-9653-4b7f-a8e3-3e316a1ffd0a.png)
![Screenshot (58)](https://user-images.githubusercontent.com/77784592/156911979-7f4bff9b-8bf7-4dce-ab4e-0787140a3aee.png)
![Screenshot (59)](https://user-images.githubusercontent.com/77784592/156911985-ccbf8096-1327-45f0-b787-abe880e39aef.png)

**Comment by VidhiBhatt01** [comment]
@bhumikatewary fill the issue template properly

**Comment by bhumikatewary** [comment]
I have updated the issue, please check
