### ISSUE TITLE
Add a travel website , with animated text.

### ISSUE THREAD

**Issue by srinjoy-26** [arpit456jain/Cool-Front-End-Templates#351]
Project description
made using HTML- CSS
HERE IS HOW IT LOOKS
I'm a GSSOC 22 contributor.
<img width="960" alt="taj" src="https://user-images.githubusercontent.com/91176055/156893513-165167a5-e386-4ebf-9b96-96489d7cca56.png">

**Comment by Sanghu01** [comment]
i want to contribute in this issue under gsscoc'22

**Comment by srinjoy-26** [comment]
I have already worked on this issue
