### ISSUE TITLE
Online Store Template

### ISSUE THREAD

**Issue by starashdeep** [arpit456jain/Cool-Front-End-Templates#353]
I have designed a unique and impressive frontend template for an online store.

Have a look at it. Hope you'll like it :)

![Screenshot (318)](https://user-images.githubusercontent.com/92468703/156899629-84c17cee-83d3-4692-9438-3ed785bc5ea7.png)

**Comment by arpit456jain** [comment]
@starashdeep

**Comment by astha2412** [comment]
@starashdeep Make a new issue when u r ready!
