### ISSUE TITLE
I want to improve pizza corner template

### ISSUE THREAD

**Issue by Areebah03** [arpit456jain/Cool-Front-End-Templates#359]
I want to improve the template for pizza corner. Please assign it to me.

**Comment by Khushi25pandey** [comment]
I am a GSSOC 2022 participant. I would like to work on the issue. Please assign it to me @Areebah03

**Comment by VidhiBhatt01** [comment]
@Areebah03 please elaborate that how will you improve it and what changes will you make

**Comment by arpit456jain** [comment]
> @Areebah03 please elaborate that how will you improve it and what changes will you make

@Areebah03

**Comment by Areebah03** [comment]
@arpit456jain I will add several css, animation effects, transform,  button, improve navbar in order to improve the design.
