### ISSUE TITLE
Improve Gym Website template

### ISSUE THREAD

**Issue by Areebah03** [arpit456jain/Cool-Front-End-Templates#362]
## **Screenshots**
![Screenshot 2022-03-06 110409](https://user-images.githubusercontent.com/85051124/156910654-4f64cb6e-5797-4bde-90f7-1e011588270d.png)

**Comment by 12345678-nishitagole** [comment]
I want to Improve this Website Template and I also have experience in CSS.

**Comment by VidhiBhatt01** [comment]
@12345678-nishitagole issues are assigned on FCFS basis, you can check out other issues/find bugs/ create issues on your own

**Comment by Sanghu01** [comment]
i want to contribute in this issue under gsscoc'22

**Comment by VidhiBhatt01** [comment]
@Sanghu01 issues are assigned on FCFS basis
