### ISSUE TITLE
Improving Food Website Template

### ISSUE THREAD

**Issue by Vanshika7902** [arpit456jain/Cool-Front-End-Templates#368]
**Issue Type:**

- [ ] Documentaion

In this project :
- Some of the key are not working(Contact Us is not smoothly scroll)
- Content is not done in Our Services section
- CSS of hover effect

## **Possible solution**

- Make Contact Us button smooth scrolled .
- Complete the content of Our Services .
- Add hover effect in Contact Us section.

**Comment by VidhiBhatt01** [comment]
@Vanshika7902 fill the issue template properly and elaborate what and how will you improve the website

**Comment by Vanshika7902** [comment]
->As in Our Services, there are three section and all are food ordering so I want to change them to Food Ordering , Combo Ordering and  Food Delivery and add relevant content and images to it .
->I want to add hover effect in the contact us section .
->On clicking on Contact Us in the nav bar it is not scrolling us to the Contact Us section ,so I wan to fix it .
