### ISSUE TITLE
Linear gradient effect on footer section.

### ISSUE THREAD

**Issue by Shobhit61730** [arpit456jain/Cool-Front-End-Templates#373]
Add linear-gradient effect on footer section will make your website very facinated.

**Comment by Shobhit61730** [comment]
Please assign this issue to me under Gssoc22 Contribution.

**Comment by arpit456jain** [comment]
@Shobhit61730 show some ss or video

**Comment by Shobhit61730** [comment]
> @Shobhit61730 show some ss or video

![image](https://user-images.githubusercontent.com/87086265/157052918-14275bd1-83b4-48c2-a467-f76980e52754.png).

1. I have changed footer part designing and add linear-gradient colors to make it more appealing and attractive.
2. I have also corrected logo image in footer top part.
