### ISSUE TITLE
Add a college fest webpage template

### ISSUE THREAD

**Issue by yashikhare** [arpit456jain/Cool-Front-End-Templates#375]
I want to add a college fest webpage template. It will contain About us and events section.
 I will be using html and css for making this college fest  template.
I am a GSSOC22  contributor.
can you please assign this issue to me?

**Comment by prer45** [comment]
I would also like to work on this issue. Please assign it to me.

**Comment by astha2412** [comment]
@yashikhare Complete this issue asap within 2-3 days....otherwise I will pass your issue to @prer45 !

**Comment by astha2412** [comment]
@prer45 r u willing to work on this issue??

**Comment by yashikhare** [comment]
yes, actually my exams were going on , so that's why i need more time

**Comment by prer45** [comment]
> @prer45 r u willing to work on this issue??

Yes I can work on the issue

**Comment by astha2412** [comment]
@yashikhare Make PR

**Comment by yashikhare** [comment]
yes mam
