### ISSUE TITLE
Template for Google Homepage

### ISSUE THREAD

**Issue by RAHULBAWA777** [arpit456jain/Cool-Front-End-Templates#380]
I want to create a google homepage template.

**Comment by astha2412** [comment]
@RAHULBAWA777 Complete this issue asap within 2-3 days....otherwise I will close your issue!

**Comment by astha2412** [comment]
Yes, @RAHULBAWA777 Make PR and link your issue so that we can track your issue with your PR! If you need any more help then tag me or any other mentor on discord!

**Comment by DEEPIKA-SUK** [comment]
@RAHULBAWA777 Make the PR otherwise this issue will get closed.

**Comment by RAHULBAWA777** [comment]
Yeah I'll make it ASAP

**Comment by DEEPIKA-SUK** [comment]
@RAHULBAWA777 make the PR by tomorrow otherwise we will close this issue!

**Comment by RAHULBAWA777** [comment]
What do you mean... I have already!!!!
And I have also received the feedback that my pr is up!!!!
