### ISSUE TITLE
pet adopting website/template

### ISSUE THREAD

**Issue by saidhanya18** [arpit456jain/Cool-Front-End-Templates#383]
I'll be making a website or template to adopt pets like dogs ..using bootstrap . User can select the pet they want and contact the owner through the details given in the website ..
![image](https://user-images.githubusercontent.com/94187364/157162676-e69d24f6-a6d9-4734-a173-d2825a873037.png)

something like this !!!
please assign this issue to me so that I can start working .

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
