### ISSUE TITLE
Bot Issue : Configuring the automated links

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#387]
- [x] Issue

## Description

- I would like to add correct links in .yml file.

## Screenshot

- Hey Admin Please assign me on this feature under GSSOC '22.

![Issue 1](https://user-images.githubusercontent.com/70098839/157218703-aa5979a2-1c4e-4165-a582-9779460df231.PNG)
'
[Link](https://github.com/arpit456jain/Cool-Front-End-Templates/issues/new)

![Issue 2](https://user-images.githubusercontent.com/70098839/157218892-2f44b4a7-3fc3-46eb-b9a1-d983c07b1de0.PNG)

[Link](https://github.com/arpit456jain/Amazing-Js-Projects/blob/master/.github/workflows/greetings.yml)

**Comment by astha2412** [comment]
@TG922 Complete this issue asap within 2-3 days....otherwise I will close your issue!

**Comment by TG922** [comment]
> @TG922 Complete this issue asap within 2-3 days....otherwise I will close your issue!

Hey @astha2412 nice to meet you !!
Actually, my Laptop fan was not working properly so, I was not able to access my laptop for long but from today I'm free to work on all issues. Tomorrow morning I will send PR regarding this !!
