### ISSUE TITLE
Hey, I would like to create a Cafe Shop website for GSSOC 22. Please assign this issue to me

### ISSUE THREAD

**Issue by Pushpita05** [arpit456jain/Cool-Front-End-Templates#390]
The website will be a landing for any cafe shop and will act as a great template for others to use. I will be using swiper.js in this to make it look more aesthetic. The website will be in light mode.

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
