### ISSUE TITLE
Developer Portfolio Template 

### ISSUE THREAD

**Issue by MannyP31** [arpit456jain/Cool-Front-End-Templates#392]
This is a developer portfolio website made using HTML , CSS and JS . It is absolutely responsive as well it has a good UI .
It has various sections such as about , skills , projects etc. Users can easily refer it to create a portfolio website of their own.

![Screenshot (628)](https://user-images.githubusercontent.com/76945004/157282277-f244e74a-c1f3-4f64-a62b-2cfa94e76165.png)

![Screenshot (629)](https://user-images.githubusercontent.com/76945004/157282242-c7b1e570-31d9-4280-8e5b-a15e8ed8c504.png)

@arpit456jain  Kindly assign me the above issue to work on .

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.

**Comment by MannyP31** [comment]
@VidhiBhatt01 yeah alr8
