### ISSUE TITLE
Netflix-Sign in-Card

### ISSUE THREAD

**Issue by gana-18** [arpit456jain/Cool-Front-End-Templates#393]
I want to add Netflix sign-in page template which is made of HTML and CSS
<img width="949" alt="image" src="https://user-images.githubusercontent.com/81679141/157286066-6140edc6-c637-4b07-9164-29df7f3d8e75.png">
@arpit456jain Kindly assign me the above issue to work on .

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
