### ISSUE TITLE
Make Food Ordering Website Responsive

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#394]
## Issue Type:

- [X] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Tasks**
 [1] Fix the nav bar
 
![image](https://user-images.githubusercontent.com/83345228/157301188-d80fd35c-c18d-405c-a75d-a397c5791181.png)

[2] Size this section properly
![image](https://user-images.githubusercontent.com/83345228/157301292-3eb04cdc-0b81-4fbf-8f51-e9ad8bb9f6fb.png)

[3] Improve the UI of the footer(You can change it completely too)
![image](https://user-images.githubusercontent.com/83345228/157301397-a945debc-9b62-4fa6-a371-5f406470b06f.png)

**Comment by trDalmi** [comment]
Hi there , i would love to work on this issue. Can u assign it to me under GSSOC22.

**Comment by Shivam-Katare** [comment]
I want to work on this issue, because responsive is one of my thing so, can you assign me this issue?

**Comment by VidhiBhatt01** [comment]
Assigned on the basis of FCFS

**Comment by arpit456jain** [comment]
@juberiya1ajaz start working on it
