### ISSUE TITLE
Add Discord App Page Clone

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Cool-Front-End-Templates#400]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

Add a clone of Discord app homepage (the one where we enter to servers & dms)

## **Possible solution**

Going to make use of
- [x] HTML
- [x] CSS
- [x] JS
- [x] Bootstrap 5

Issue created under GSSoC'22 contributions

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
