### ISSUE TITLE
Add a website template for book readers

### ISSUE THREAD

**Issue by Nitya-S27** [arpit456jain/Cool-Front-End-Templates#401]
I want to add a website template for book readers which I made.
Here's the link : https://nitya-s27.github.io/ReadMe/

This issue is in context with the conflicts occured in the issue  #357

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
