### ISSUE TITLE
login template

### ISSUE THREAD

**Issue by leesha19** [arpit456jain/Cool-Front-End-Templates#402]
## Issue Type: feature request 

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.
- 

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

i want to add a cool login page template using html css and javascript

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
