### ISSUE TITLE
Cafeteria Webpage

### ISSUE THREAD

**Issue by Keyurchaniyara** [arpit456jain/Cool-Front-End-Templates#411]
## Issue Type:

- [ ] frontend page
- [ ] making this page Responsive

## **Possible solution**

- Hello

I am a GSSoC22 contributor. I will be delighted to make fully responsive website on cafeteria. Please do assign this to me.

Thank You :)

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
