### ISSUE TITLE
Grocery Store Webpage

### ISSUE THREAD

**Issue by YatreeLadani** [arpit456jain/Cool-Front-End-Templates#413]
## Issue Type:

- [ ] Responsive frontend page

## **Possible solution**

I am a GSSoC22 contributor. I would like to make responsive website on Grocery store.

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.

**Comment by YatreeLadani** [comment]
Please reopen this issue and assign it to me. @VidhiBhatt01
