### ISSUE TITLE
Amazon Prime Video login page clone

### ISSUE THREAD

**Issue by yellowberard** [arpit456jain/Cool-Front-End-Templates#414]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- I made clone amazon prime video login page clone with HTML and css .

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.

**Comment by yellowberard** [comment]
@VidhiBhatt01 can this issue be reopen?
