### ISSUE TITLE
Youtube Clone (Front-End)

### ISSUE THREAD

**Issue by mrkc2303** [arpit456jain/Cool-Front-End-Templates#415]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

I have a project Youtube-Clone made by HTML, CSS & Vanilla JS

## **Possible solution**

I have made the project for the same

## **Screenshots**

<img width="547" alt="Screenshot 2022-03-11 at 11 21 54 PM" src="https://user-images.githubusercontent.com/67221487/157922962-562e4cf1-4b28-4475-bc47-e9b588c51e1c.png">
<img width="1511" alt="Screenshot 2022-03-11 at 11 21 25 PM" src="https://user-images.githubusercontent.com/67221487/157923114-390ca1d7-6df2-467b-a0f8-efdc76bdc019.png">

Kindly Assign me this issue!
Thanks

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
