### ISSUE TITLE
Recruitment website

### ISSUE THREAD

**Issue by prachi1211** [arpit456jain/Cool-Front-End-Templates#417]
**Issue Type:**

- [ ] Responsive frontend page
- [ ] Add download resume button

**Possible solution**

I am a GSSoC22 contributor. I would like to make responsive Recruitment website.

Thank you

**Comment by yashbhardwaj11** [comment]
I want to work on this issue PA can you assign this issue to me

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.

**Comment by prachi1211** [comment]
I am a GSSoC22 contributor. Please reopen this issue and assign it to me.
