### ISSUE TITLE
CSS Grid Template

### ISSUE THREAD

**Issue by KushagraJain58-cmd** [arpit456jain/Cool-Front-End-Templates#418]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- I have made a CSS template using grid.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![Grid Master - Google Chrome 11-03-2022 23_33_34](https://user-images.githubusercontent.com/81035005/157924524-c6a0262b-470c-4e50-ac0b-8f7c3126fd86.png)

**Comment by VidhiBhatt01** [comment]
Issues for new projects will be assigned next week. This week we are only focussing on improving the existing ones. You can raise this issue / reopen it next week.
