### ISSUE TITLE
Dynamic Weather App using ReactJS

### ISSUE THREAD

**Issue by SidharthSarangi** [arpit456jain/Cool-Front-End-Templates#422]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

will be adding a dynamic weather app integrated by ReactJS with the help of openweatherAPI 
kindly assign this issue to me.
I am a GSSOC'22 participant.

**Comment by VidhiBhatt01** [comment]
We are not including projects with React JS as of now
