### ISSUE TITLE
Job_finding_website_responsive

### ISSUE THREAD

**Issue by Richadxt** [arpit456jain/Cool-Front-End-Templates#428]
I want design a job finding responsive website using Html,Css,Javascript n Bootstrap.please assign me to work on this task.

**Comment by VidhiBhatt01** [comment]
@Richadxt If this project contains a significant amount of JS, I would suggest that you raise the issue in the amazing JS projects repo.

**Comment by Richadxt** [comment]
Thank you! @VidhiBhatt01 for assigning me..
