### ISSUE TITLE
Online Delivery App

### ISSUE THREAD

**Issue by BinilTomJose1278** [arpit456jain/Cool-Front-End-Templates#429]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
@BinilTomJose1278 fill the issue template properly

**Comment by VidhiBhatt01** [comment]
@BinilTomJose1278
