### ISSUE TITLE
I want to add my Webpage to the specific Website.

### ISSUE THREAD

**Issue by VishweshDeshpande28** [arpit456jain/Cool-Front-End-Templates#432]
I have created a Cool Template about Gaming Website and also want to add up that to this project.

**Vishwesh Deshpande,
I'm GSSoC'2022 Contributor.** 

Kindly assign me this work.

**Comment by Dhananjaysharma207** [comment]
I have created a Cool Template about commercial website and also want to add up that to this project.
Dhananjay Sharma
Participant GSSOC'22

**Comment by VidhiBhatt01** [comment]
> You wish! 😃 @VidhiBhatt01

??

you can attach whatever you find comfortable

**Comment by arpit456jain** [comment]
> I have created a Cool Template about commercial website and also want to add up that to this project. Dhananjay Sharma Participant GSSOC'22

make a new issue
