### ISSUE TITLE
Add footer in Welcome to Lucknow page

### ISSUE THREAD

**Issue by ayushim13** [arpit456jain/Cool-Front-End-Templates#435]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- I would add a footer to this page to make it more attractive.

## **Possible solution**

- footer

## **Screenshots**

<img width="1440" alt="Screenshot 2022-03-14 at 8 14 20 PM" src="https://user-images.githubusercontent.com/78809695/158197024-2c82b546-a06a-44e2-bf11-91d73bde570b.png">

**Comment by DEEPALI-SUK** [comment]
@ayushim13 go ahead.
