### ISSUE TITLE
Shoe Store Website

### ISSUE THREAD

**Issue by RajAdwaita** [arpit456jain/Cool-Front-End-Templates#437]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.
- I just started working on a cool frontend template for a shoe store and would love to have my work included in this project.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/76047644/158399717-e990c75e-931b-42d8-b391-f4306c08de5f.png)

**Comment by arpit456jain** [comment]
have u made it already ?

**Comment by RajAdwaita** [comment]
no bro I am working on it that was just the landing page

**Comment by RajAdwaita** [comment]
Hey Admin can I make this template a part of your mega project

**Comment by VidhiBhatt01** [comment]
> I am sorry but if the issue is closed does it mean that it goes invalid

Yes, invalid as of now. You can reopen this again in the future if we decide to include React Projects too. Sorry for the inconvenience!
