### ISSUE TITLE
Build a Cool Calculator

### ISSUE THREAD

**Issue by SwarupKMondal** [arpit456jain/Cool-Front-End-Templates#441]
**Create a Calculator**

**Tech Used**
1. Html
2. Css
3. Javascript

I am a GSSOC'22 Participant.
I want to work in this issue.
Please assign it to me.

**Comment by hrushi2003** [comment]
@SwarupKMondal 
Can you assign me to do this calculator

**Comment by hrushi2003** [comment]
Can you assign me the project to do

**Comment by SwarupKMondal** [comment]
I am working on this project and I was the one who raised the issue. Kindly issue it to me
