### ISSUE TITLE
Animated FrontEnd Website

### ISSUE THREAD

**Issue by RajAdwaita** [arpit456jain/Cool-Front-End-Templates#444]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.
- Want to add a new frontEnd template having some animations and SVG based images.

## **Possible solution**

- Describe the solution you thought of.
- I have planned to start working on a cool frontEnd design that included some animations and vector graphics and I would like to add my frontEnd template to your repo.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
- I have planned the basic layout, but I need some time to make the final design and add it to the repository.

**Comment by VidhiBhatt01** [comment]
@RajAdwaita fill the issue template properly

**Comment by RajAdwaita** [comment]
Sorry Maam but do you want me to attach some preliminary screenshots of the website I am going to contribute

**Comment by RajAdwaita** [comment]
@VidhiBhatt01 MAAM this is the type of website I am planning to work on
![Screenshot 2022-03-17 213327](https://user-images.githubusercontent.com/76047644/158842510-c432719b-5bc4-4616-b7a5-1dcfe40968c7.png)

**Comment by RajAdwaita** [comment]
https://silly-shockley-17e80a.netlify.app/

**Comment by RajAdwaita** [comment]
Hello, I have finally made this template and I hope my work will be included in the Cool Front End Templates Project

**Comment by VidhiBhatt01** [comment]
Go on and raise the PR :)

**Comment by RajAdwaita** [comment]
I have pushed the changes could you please check it

**Comment by RajAdwaita** [comment]
PR -  #485
