### ISSUE TITLE
Change the background to dark mode in technology page and also add more pictures and content to page

### ISSUE THREAD

**Issue by akritisrivastava2** [arpit456jain/Cool-Front-End-Templates#445]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- background change to dark mode and also add more pictures and content to page
![technology](https://user-images.githubusercontent.com/86703150/158584781-d4fc6601-c0f2-40de-84dc-9dabd859f434.jpg)
![tech2](https://user-images.githubusercontent.com/86703150/158585476-e1ac110a-28c7-4267-9c9a-4f2ceb3a76c9.jpeg)

**Comment by VidhiBhatt01** [comment]
@akritisrivastava2 which project are you talking about? Kindly attach an SS of that page for easy reference

**Comment by akritisrivastava2** [comment]
added SS of the page and edited the issue

**Comment by DEEPIKA-SUK** [comment]
@akritisrivastava2 Make the PR otherwise this issue will be closed.

**Comment by akritisrivastava2** [comment]
ok will be doing soon
