### ISSUE TITLE
Structure All the projects 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#448]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

1. lots of project having images in root folder so make a new folder named img and put all images in that and edit path of images in file properly.

2.must check every project have a preview.png or not 

3.It should be png not jpeg or any other format 

4.make 1st letter of project capital and change  it in json file also

**Comment by TG922** [comment]
Hey, can you assign this issue to me?

Some projects don't have any preview image
Like this: https://github.com/arpit456jain/Cool-Front-End-Templates/tree/master/project2
