### ISSUE TITLE
Check All the projects having plagiarism 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#450]
Check All the projects having plagiarism list them here 
list their hosted link of my repo and the original template

**Comment by shubhamlakheraa** [comment]
Hey can I work on this issue.

**Comment by shubhamlakheraa** [comment]
Hey @arpit456jain, I  have concluded my inspection of the plagiarised code used in the Cool-Front-End-Templates project. Though there exist many projects which are based on the same topic their code is different more than 50% and are different in terms of designs. 
My inspection included:
1. Checking the code for projects whose topics are the same or different.
2. Checking the design for projects whose topics are the same or different.

In Code I checked for:
1.  Naming Conventions used.
2. Header / Footer Structure
3.  Navigation Bar (if present)
4. Comments (if used)
5. Code Structure overall (mainly checking any similarity in div tags used )

**Comment by arpit456jain** [comment]
@shubhamlakheraa great just maintain a list of templates' , their live links of our repo and link of original template u can have a meet with mentors

**Comment by shubhamlakheraa** [comment]
Ok sure  @arpit456jain

**Comment by DEEPIKA-SUK** [comment]
@shubhamlakheraa Make the PR

**Comment by shubhamlakheraa** [comment]
Hey @DEEPIKA-SUK, I don't have any changes in the main repository codebase so I'm not sure what I need to make a PR for.
Till now what I understand is that I need to maintain a list of all the templates with their link.
Am I missing something which you can help me with?

**Comment by arpit456jain** [comment]
> Hey @DEEPIKA-SUK, I don't have any changes in the main repository codebase so I'm not sure what I need to make a PR for. Till now what I understand is that I need to maintain a list of all the templates with their link. Am I missing something which you can help me with?

@shubhamlakheraa just share the list with us and then we will mark some templates and u have to delete the and then u can make PR

**Comment by arpit456jain** [comment]
@shubhamlakheraa r u sharing the list ?

**Comment by shubhamlakheraa** [comment]
Yes I just need to update the list 30 mins max.

**Comment by shubhamlakheraa** [comment]
[Cool Front End Templates.docx](https://github.com/arpit456jain/Cool-Front-End-Templates/files/8401911/Cool.Front.End.Templates.docx)

**Comment by shubhamlakheraa** [comment]
Hey, @arpit456jain Full list of projects with their repository links is added.
[Cool Front End Templates.docx](https://github.com/arpit456jain/Cool-Front-End-Templates/files/8401927/Cool.Front.End.Templates.docx)

**Comment by arpit456jain** [comment]
@shubhamlakheraa 
i think u didn't understand my concern let me tell u again 

i want to filter out those template which are downloaded from anywhere like codepen or something else or from any othet github repo.

ignore the cloned once for now 

and make 3 cols 
1. name
2. folder url
3. deployed link

and make a separate list of similar templates
