### ISSUE TITLE
user interactive register form required here

### ISSUE THREAD

**Issue by myhacktech** [arpit456jain/Cool-Front-End-Templates#452]
## Issue Type:

 Feature Request

## **Describe the bug**
An interactive form could be designed here for users ,so that they can sign up easily.

- A clear and concise description of what the bug is.

## **Possible solution**

A form to be created

## **Screenshots**
![form arpit jain](https://user-images.githubusercontent.com/86517958/158723527-c648eec5-144a-4a08-8504-650d26d4f68e.png)

- If applicable, add screenshots to help explain your problem.

**Comment by Manik-Aggarwal** [comment]
@myhacktech @arpit456jain please assign me this issue, I want to work on it.

**Comment by myhacktech** [comment]
@arpit456jain can you please assign me this task, i have been trying to add the new features that can be included here?

**Comment by arpit456jain** [comment]
@myhacktech I m not getting what you want to do please elaborate

**Comment by myhacktech** [comment]
> ![image](https://user-images.githubusercontent.com/83345228/158872169-2d12c794-c88e-45c6-bb88-abf58987151c.png) @myhacktech am assigning you. You can make a template for this but you need to enhance the UI specially of the part attached in SS. Current one is very poor.

sure

**Comment by juberiya1ajaz** [comment]
can I work on this ? I would love to solve this issue. I can improve the UI as well as make this responsive.

**Comment by arpit456jain** [comment]
> can I work on this ? I would love to solve this issue. I can improve the UI as well as make this responsive.

@juberiya1ajaz check out other templates if they are not responsive u can create a issue for it and mention us
