### ISSUE TITLE
work on the buttons of the website as they donot appear good on hovering and also add ome page link to the logo

### ISSUE THREAD

**Issue by Phalak-Sharma** [arpit456jain/Cool-Front-End-Templates#456]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**
work on the buttons of the website as they donot appear good on hovering and also add ome page link to the logo

- A clear and concise description of what the bug is.
<img width="1230" alt="Screenshot 2022-03-18 at 6 03 53 PM" src="https://user-images.githubusercontent.com/36873064/159004264-d4a30fad-a72a-4d5a-8d11-bae331c6d8cb.png">

## **Possible solution**
On hovering, a good transition and clicking on logo brings to home page
- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
not needed for noe
