### ISSUE TITLE
Adding a Anime Template

### ISSUE THREAD

**Issue by RajatBhaskare7** [arpit456jain/Cool-Front-End-Templates#462]
A creative anime website UI with animation and hover effects and creative cards and many more things

**Comment by RajatBhaskare7** [comment]
assign me this task

**Comment by arpit456jain** [comment]
@RajatBhaskare7 first make the template show us if its up to the  mark then only we can assign u

**Comment by VidhiBhatt01** [comment]
@RajatBhaskare7

**Comment by RajatBhaskare7** [comment]
yeah I have completed templated soon going to raise PR

**Comment by DEEPIKA-SUK** [comment]
@RajatBhaskare7 make PR by today otherwise we will close the issue.

**Comment by astha2412** [comment]
@RajatBhaskare7 Make new PR when u r Ready!
