### ISSUE TITLE
Add a project section and a service section to Tailwind Portfolio 

### ISSUE THREAD

**Issue by ayushim13** [arpit456jain/Cool-Front-End-Templates#463]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Project and service section missing.

## **Possible solution**

- Adding project and service section to make the portfolio website better.

## **Screenshots**

<img width="1440" alt="Screenshot 2022-03-19 at 6 06 42 PM" src="https://user-images.githubusercontent.com/78809695/159121390-64969bec-0b9a-49e1-a1b4-02f77f1c9750.png">
<img width="1440" alt="Screenshot 2022-03-19 at 6 06 16 PM" src="https://user-images.githubusercontent.com/78809695/159121393-0cb75f2d-96e8-4171-8d58-f092d0f35851.png">

I want to work on this issue under GSSOC. Please assign it to me.

**Comment by DEEPIKA-SUK** [comment]
@ayushim13 any update? Make the PR as soon as possible

**Comment by ayushim13** [comment]
@DEEPIKA-SUK  I'm working on it....gonna make PR soon.

**Comment by ayushim13** [comment]
@DEEPIKA-SUK working on it, will make the pr soon.

**Comment by DEEPIKA-SUK** [comment]
@ayushim13 make the PR by today otherwise we will close this issue.

**Comment by astha2412** [comment]
@ayushim13 Make issue again when u r ready with your code!
