### ISSUE TITLE
Add a new templet to this project

### ISSUE THREAD

**Issue by ayushim13** [arpit456jain/Cool-Front-End-Templates#464]
I want to add a new templet (Fitness theme templet) to this project under GSSOC.

<img width="1440" alt="Screenshot 2022-03-27 at 1 48 36 AM" src="https://user-images.githubusercontent.com/78809695/160255737-1755062e-1c59-491a-b1a8-b237ad6a998c.png">

<img width="1437" alt="Screenshot 2022-03-27 at 1 47 08 AM" src="https://user-images.githubusercontent.com/78809695/160255731-54be3134-90f2-4810-9c0d-c23124ff3436.png">

**Comment by astha2412** [comment]
@ayushim13 Add ss or Video in your issue!
