### ISSUE TITLE
Add new template containing different food items.

### ISSUE THREAD

**Issue by RavishaNewase** [arpit456jain/Cool-Front-End-Templates#465]
Please assign me this under GSSoC'22.

**Comment by SonikeshKumar14** [comment]
plz assign me i want to work on this issue

**Comment by astha2412** [comment]
@RavishaNewase  Plz add some ss or video...we have already many food websites.

**Comment by dvlsatya** [comment]
PLEASE ASSIGN AND I WANT TO WORK ON THIS ISSUE

**Comment by DEEPIKA-SUK** [comment]
@dvlsatya currently we are not assigning any issue regarding new templates so I am closing this issue, you can open this issue after few days.
