### ISSUE TITLE
Make the template responsive

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#466]
Using media queries make the Amol Shelkhe portfolio template responsive for all screen sizes.
Folder link: https://github.com/arpit456jain/Cool-Front-End-Templates/tree/master/AmolShelke-portfolio

![image](https://user-images.githubusercontent.com/83345228/159130419-e52f5ad2-1687-4159-9391-57df1632459c.png)

**Comment by KhushiRana2003** [comment]
I am a participant under GSSOC 2022. I would like to work on the issue. Please assign it to me..

**Comment by DEEPIKA-SUK** [comment]
@KhushiRana2003 Go ahead and try to complete the task as soon as possible.

**Comment by KhushiRana2003** [comment]
Yaah Thanks.. I will do it upto 27 march. Thanks for assigning it to me.

**Comment by Sakshi-1701** [comment]
Hey @DEEPIKA-SUK 
If this issue is still up for the grab, I'd love to work on this.

**Comment by arpit456jain** [comment]
@KhushiRana2003 updates ??

**Comment by KhushiRana2003** [comment]
@arpit456jain Sir I will Do it within two more days..

**Comment by KhushiRana2003** [comment]
Sir give me 2 days more bcoz i am busy in my curriculum in college... Some
of the project us left so I need 2 more days.. And i will definitely do it
after 2 days ...

**Comment by jyotivakare33** [comment]
@arpit456jain Can you assign me this issue if it is still open
