### ISSUE TITLE
Make Template Responsive

### ISSUE THREAD

**Issue by DEEPALI-SUK** [arpit456jain/Cool-Front-End-Templates#469]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

There is a folder named Admin Dashboard in the Cool-Front-End-Templates repo. Make that template fully responsive.

## **Screenshots**
- Desktop view
![Screenshot (67)](https://user-images.githubusercontent.com/64724041/159132913-513ed6f5-2705-43b2-96cb-4dacbe85e487.png)
- Mobile View
![Screenshot (68)](https://user-images.githubusercontent.com/64724041/159132937-43a18e41-ce78-4c1f-9091-bd162cd992be.png)

**Comment by DEEPIKA-SUK** [comment]
@juberiya1ajaz any update? Make the PR as soon as possible

**Comment by piyusha2001** [comment]
Can you assign me this under GSSoC'22 ?

**Comment by PraveenaPulagam** [comment]
can you assign me this project?

**Comment by VidhiBhatt01** [comment]
Assigned

**Comment by PraveenaPulagam** [comment]
okk

**Comment by DEEPIKA-SUK** [comment]
@PraveenaPulagam Make PR.
