### ISSUE TITLE
Make Template Responsive

### ISSUE THREAD

**Issue by DEEPALI-SUK** [arpit456jain/Cool-Front-End-Templates#470]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

There is a folder named Apple Webiste UI Clone in the Cool-Front-End-Templates repo. Make that template fully responsive.
Desktop view

## **Screenshots**

- Mobile View
![Screenshot (69)](https://user-images.githubusercontent.com/64724041/159133627-72815a7f-9ab4-4fdf-af44-008b191250c4.png)

- Desktop View
![Screenshot (70)](https://user-images.githubusercontent.com/64724041/159133645-f4335296-a3f7-46a2-8db8-d5e21a8a3488.png)

**Comment by Shivam-Katare** [comment]
Hey @DEEPALI-SUK I want to work on this issue, So can you assign me this issue.

**Comment by Sakshi-1701** [comment]
Hello @DEEPALI-SUK 
I would love to work on this.
It would be great if you could assign this issue to me.

**Comment by DEEPALI-SUK** [comment]
@Shivam-Katare any updates?

**Comment by Shivam-Katare** [comment]
@DEEPALI-SUK Yes, I am working on it,half work is done and half work will done shortly.

**Comment by Shivam-Katare** [comment]
Hey, @DEEPALI-SUK My laptop isn't responding correctly due to some hardware problem, So I can't solve this issue on time and I don't want to late this issue more. So, you can "Unassign me" from this issue. I am so sorry for taking your time hope you'll understand my problem.

**Comment by DEEPALI-SUK** [comment]
> Hey, @DEEPALI-SUK My laptop isn't responding correctly due to some hardware problem, So I can't solve this issue on time and I don't want to late this issue more. So, you can "Unassign me" from this issue. I am so sorry for taking your time hope you'll understand my problem.

yeah no problem!

**Comment by AnweshaRoses** [comment]
Hello I would like to work on this. Can you please assign it to me :)
