### ISSUE TITLE
Template preview images looks stretched

### ISSUE THREAD

**Issue by rockingrohit9639** [arpit456jain/Cool-Front-End-Templates#471]
The preview image of all templates looks stretched which kinda not look good in UI. I suggest making the images not stretched which will immediately improve the UI. 

## **Screenshots**

![image](https://user-images.githubusercontent.com/40729749/159148418-22a86e6a-c0a5-4e96-a923-3f0e03581ad6.png)

**Comment by arpit456jain** [comment]
no need for now
