### ISSUE TITLE
Microsoft Teams -> teams page clone

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Cool-Front-End-Templates#475]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

I would like to add a clone of one of the microsoft teams page (the page where the groups are listed)

## **Possible solution**

- The page will be responsive as the one in the desktop web app.
- Page will have Light & Dark mode implemented.
- Page will make use of HTML, CSS, Bootstrap5.

Issue made under GSSoC'22 contributions.

**Comment by DEEPIKA-SUK** [comment]
@XZANATOL any update?

**Comment by XZANATOL** [comment]
Ye, I'm almost finished with the main UI and then gonna implement Light/Dark Themes. It should take me a day or 2 max.
