### ISSUE TITLE
Developing Tiktok Clone

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#478]
## Issue Type:
- [ ]  Bug Report
- [x]  Feature Request
- [ ]  Documentaion

will be adding the Tiktok clone using HTML, CSS, JS
Please assign me to this, I am a GSSOC'22 participant

**Comment by Shweta-Rani1** [comment]
I'm a GSSoC participant. I would like to work on this project.
Can you please assign me the project!
It would look like this-

![Tiktok Web App Clone](https://user-images.githubusercontent.com/80149419/159441879-c3acf6a6-d2c0-4258-959b-40143aa79103.jpg)

**Comment by VidhiBhatt01** [comment]
Cool

**Comment by DEEPIKA-SUK** [comment]
@Shweta-Rani1 any update? Make the PR as soon as possible

**Comment by TG922** [comment]
are you working on this @Shweta-Rani1 ??

@VidhiBhatt01 you can also ask her if she is doing it or not
If not then i can work on it

**Comment by arpit456jain** [comment]
@TG922
