### ISSUE TITLE
Add Organic Business Home Page 

### ISSUE THREAD

**Issue by kaustav202** [arpit456jain/Cool-Front-End-Templates#480]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

A template for the landing page of a Organic Retail Website made using cool parallax effects using a clean and beautiful UI.

## **Possible solution**

Implemented

## **Screenshots**

![Uploading Screenshot (579).png…]()

![Uploading Screenshot (580).png…]()

**Comment by kaustav202** [comment]
Can I be assigned this issue

**Comment by kaustav202** [comment]
Here are some screenshots that failed to upload earlier.

![o1](https://user-images.githubusercontent.com/89788120/159407345-fd2a8787-a978-45a7-a99b-906efa337f98.png)

![o2](https://user-images.githubusercontent.com/89788120/159408548-d8bdd681-b2c6-493e-bc1a-e9c14a1621e8.png)

**Comment by arpit456jain** [comment]
> Hello there!👋, @kaustav202 Welcome to the Cool-Front-End_Templates project!🚀⚡Thank you and congrats🎉 for opening issue in this project. Please make sure not to start working on the issue, unless you get assigned to it.😄 first make the template and show us either by video or live demo, if its up to the mark and does not contain any plagiarism then only we can assign u

@kaustav202 read this

**Comment by kaustav202** [comment]
> > Hello there!👋, @kaustav202 Welcome to the Cool-Front-End_Templates project!🚀⚡Thank you and congrats🎉 for opening issue in this project. Please make sure not to start working on the issue, unless you get assigned to it.😄 first make the template and show us either by video or live demo, if its up to the mark and does not contain any plagiarism then only we can assign u

Okay please assign me this

**Comment by VidhiBhatt01** [comment]
Assigned

**Comment by DEEPIKA-SUK** [comment]
@kaustav202 make the PR by today otherwise we will close this issue.

**Comment by kaustav202** [comment]
PR linked please review @DEEPIKA-SUK
