### ISSUE TITLE
Add a Tourist Landing Page

### ISSUE THREAD

**Issue by chickenCHRISpy** [arpit456jain/Cool-Front-End-Templates#481]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by chickenCHRISpy** [comment]
![image](https://user-images.githubusercontent.com/54064653/159539320-154fff6b-9b78-4ed3-a976-95a050a1069c.png)

**Comment by sophiastr** [comment]
Hello, i want to deal with this issue.
Can i have it, please?

**Comment by arpit456jain** [comment]
@chickenCHRISpy @sophiastr
