### ISSUE TITLE
Add Starbucks Landing Page

### ISSUE THREAD

**Issue by piyushsonawane07** [arpit456jain/Cool-Front-End-Templates#483]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

**Comment by piyushsonawane07** [comment]
![image](https://user-images.githubusercontent.com/69463163/159540200-9c5084e0-2f8d-4ff6-945a-85e16126ce17.png)

**Comment by Estheryu991** [comment]
wo ist die Api?
