### ISSUE TITLE
Creative Agency Website

### ISSUE THREAD

**Issue by Piyush-Aman** [arpit456jain/Cool-Front-End-Templates#487]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![Screenshot (56)](https://user-images.githubusercontent.com/75135026/159777887-2a119c82-c967-4990-8bd8-156d6bddcd58.png)

- If applicable, add screenshots to help explain your problem.

**Comment by astha2412** [comment]
@Piyush-Aman Complete it Asap!
