### ISSUE TITLE
[Add] Retaurant landing page

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [arpit456jain/Cool-Front-End-Templates#488]
<h2>Am GSSOC '22 Contributor..</h2>
...
## Issue Type:
 

-  Feature Request

## **Possible solution**

I want to add the restaurant website landing page

## **Screenshots**
![Screenshot from 2022-03-24 17-13-52](https://user-images.githubusercontent.com/85225156/159909419-d457f8e5-47d7-4d60-b0a6-79ba448ffb85.png)

```
```
![Screenshot from 2022-03-24 17-15-10](https://user-images.githubusercontent.com/85225156/159909976-5b266021-3965-4e6f-9e32-1e7e279eb835.png)
```
```

![Screenshot from 2022-03-24 17-15-20](https://user-images.githubusercontent.com/85225156/159909871-fadc342b-c1b9-4b7c-a197-b7cdacecc311.png)

**Comment by arpit456jain** [comment]
> Hello there!👋, @Vikash-8090-Yadav Welcome to the Cool-Front-End_Templates project!🚀⚡Thank you and congrats🎉 for opening issue in this project. Please make sure not to start working on the issue, unless you get assigned to it.😄 first make the template and show us either by video or live demo, if its up to the mark and does not contain any plagiarism then only we can assign u

.

**Comment by Vikash-8090-Yadav** [comment]
Ok sure ..i will make the video and uplaod it..
Thank's for the comment..😄

**Comment by astha2412** [comment]
@Vikash-8090-Yadav ??????Complete this issue asap!
