### ISSUE TITLE
Add a grocery shopping Template

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [arpit456jain/Cool-Front-End-Templates#490]
## Issue Type: Add template for grocery shopping 

- [ ] Feature Request

## **I want to add a grocery shopping template by using html ,css ,javascript and bootstrap .Kindly assign me this issue**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
[
![grocery](https://user-images.githubusercontent.com/89297894/159956492-88eed6f2-4651-4333-b9f2-10d4c5dca67b.png)
](url)

**Comment by AsmaIbrahimButt** [comment]
Kindly assign me this issue.

**Comment by arpit456jain** [comment]
> Hello there!👋, @AsmaIbrahimButt Welcome to the Cool-Front-End_Templates project!🚀⚡Thank you and congrats🎉 for opening issue in this project. Please make sure not to start working on the issue, unless you get assigned to it.😄 first make the template and show us either by video or live demo, if its up to the mark and does not contain any plagiarism then only we can assign u

.

**Comment by astha2412** [comment]
@AsmaIbrahimButt Complete your issue Asap!!!

**Comment by AsmaIbrahimButt** [comment]
Hi @astha2412 .Would appreciate to have a review on this pull request https://github.com/arpit456jain/Cool-Front-End-Templates/pull/578
Thanks.

**Comment by AsmaIbrahimButt** [comment]
@arpit456jain  ,yeah,Thanks
