### ISSUE TITLE
Adding About, Services, Menu & Contact Page on "Food Template" Website

### ISSUE THREAD

**Issue by aditiitomar** [arpit456jain/Cool-Front-End-Templates#491]
## Issue Type:
- _Feature Request_

## **Describe the bug**

-  _Currently, there is no About, Services, Menu, Contact Page on [Food Template Website](https://cool-front-end-templates.netlify.app/food_template/#). I would like to create all the four pages with HTML & CSS_.

## **Screenshots**
![FoodTemplate](https://user-images.githubusercontent.com/80448500/159966204-a2fd9337-548a-427c-ae93-e7c5cafb3ef4.png)

**Comment by aditiitomar** [comment]
Hey, @arpit456jain Can I work on this issue?

**Comment by arpit456jain** [comment]
sure @aditiitomar

**Comment by astha2412** [comment]
@aditiitomar Complete this issue Asap!!!
