### ISSUE TITLE
Making yoga template fully responsive

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [arpit456jain/Cool-Front-End-Templates#492]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**
There is a folder named Yoga template in the Cool-Front-End-Templates repo. Make that template fully responsive.

## **Screenshots**

![Screenshot (94)](https://user-images.githubusercontent.com/64724039/159981995-5f6598a7-d4fb-4f90-88b9-cff635e16cfc.png)

**Comment by abhinav80066** [comment]
I Would like to work on this issue under GSSoC'22.

**Comment by arpit456jain** [comment]
@abhinav80066 go ahead

**Comment by VidhiBhatt01** [comment]
@abhinav80066 do you have any updates? If the PR is not submitted within 3/4 days, the issue would be passed onto to you @pujthej

**Comment by pujthej** [comment]
@VidhiBhatt01 Hi it's been 7 days can you assign this to me?

**Comment by arpit456jain** [comment]
@pujthej go ahead
