### ISSUE TITLE
Want to add a books website bootstrap template

### ISSUE THREAD

**Issue by Nitya-S27** [arpit456jain/Cool-Front-End-Templates#497]
I want to add a website template for book readers which I made.
Here's the link : https://nitya-s27.github.io/ReadMe/

**Comment by arpit456jain** [comment]
increase the font size and make a PR
![screencapture-nitya-s27-github-io-ReadMe-2022-03-26-17_53_08](https://user-images.githubusercontent.com/55352601/160239256-ce41d71c-9d37-4306-8a1b-347d8b46bc26.png)
