### ISSUE TITLE
css water wave background 

### ISSUE THREAD

**Issue by iamrahulmahato** [arpit456jain/Cool-Front-End-Templates#498]
## Issue Type:

- [x] Feature Request
- [x] Documentaion

## **Possible solution**

It will be a water wave background made with CSS and Html

## **Screenshots**

![wave](https://user-images.githubusercontent.com/49890655/160241398-02ae76a7-15af-4665-929b-a9e53494b1cc.jpeg)

**Comment by VidhiBhatt01** [comment]
Raise this issue in amazing css effects repo if it is not already present there
