### ISSUE TITLE
 Adding my Portfolio in Cool Templates

### ISSUE THREAD

**Issue by DinahWorld** [arpit456jain/Cool-Front-End-Templates#500]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

I want to add my portfolio to your project
My portfolio :  https://dinahworld.xyz/

## **Screenshots**
![Screenshot_2022-03-26-46_1890x1018](https://user-images.githubusercontent.com/88936472/160250648-366e98ae-2e2e-4954-8028-2b43e53ac44b.png)

![Screenshot_2022-03-26-55_1890x1018](https://user-images.githubusercontent.com/88936472/160250652-6a2726e6-dd99-4177-a44a-020b54218341.png)

**Comment by astha2412** [comment]
@DinahWorld Make issue again when u ready with your code!
