### ISSUE TITLE
Bug : Bottom up Top button doesn't disappear in the GymWebsite

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#502]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Bottom-up Top doesn't disappear in the gym website after scrolling back to the top. 
- I can fix it please assign it to me under GSSOC'22.

## **Screenshots**

![Image26](https://user-images.githubusercontent.com/70098839/160259180-aeb0525a-81a2-4bf0-9e73-320d46033abb.PNG)

**Comment by TG922** [comment]
I have almost worked on it will send PR soon

**Comment by astha2412** [comment]
Complete it asap!

**Comment by TG922** [comment]
Ok @astha2412
