### ISSUE TITLE
Improvement : Adding fixed header

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#503]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Adding a fixed header in **AmolShelke-Portfolio** will increase the UX of the website.
- I can fix it please assign it to me under GSSOC'22.

## **Screenshots**

![Image27](https://user-images.githubusercontent.com/70098839/160259325-8bde66f9-7998-4fc6-a159-ffed2c604555.PNG)

**Comment by VidhiBhatt01** [comment]
Ig this isn't responsive. I had created an issue for it earlier, do that too if it's not yet completed

**Comment by TG922** [comment]
Yes, @VidhiBhatt01 will be the responsive header. Thanks for assigning !!

**Comment by VidhiBhatt01** [comment]
Puri website hi responsive nai hai 🙃

**Comment by TG922** [comment]
> Puri website hi responsive nai hai 🙃

Aree mai toh fas gya 🙃
Accha Thk ho jaayega ye bhi simple website hai !!

But level??

**Comment by TG922** [comment]
> Ig this isn't responsive. I had created an issue for it earlier, do that too if it's not yet completed

Issue number?? I will rename this issue if it's not completed

**Comment by TG922** [comment]
> Ig this isn't responsive. I had created an issue for it earlier, do that too if it's not yet completed

Oops 🙃
Ok I can do it easily it is single-page website
Issue number?? I will rename this issue if previous issue mentioned by you is not completed

**Comment by VidhiBhatt01** [comment]
#466, someone is working ig on this. I would suggest you wait for 1/2 days, pull the changes and then start working

**Comment by TG922** [comment]
@VidhiBhatt01 Let her work !! 
This program was meant for girls. But still, there are majority of boys participating and girls get less number of chances.

I can work on other issues.

**Comment by TG922** [comment]
But I have one doubt is there any score provided to the person who created the issue but not assigned??

**Comment by astha2412** [comment]
ok @TG922

**Comment by VidhiBhatt01** [comment]
@TG922 any updates?

**Comment by TG922** [comment]
Sorry for the delay I was busy in SIH 22 and will complete it ASAP. I know it's too late to close this issue.

**Comment by TG922** [comment]
Sorry, I'm having exams from Monday onwards I will not be able to contribute right now. Make this issue open for all !!

Still, I enjoyed it a lot while exploring and contributing to open-source projects.
