### ISSUE TITLE
Bug : Adding working contact page and about page

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#504]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Currently, there is no About, Contact Page on the **Home Design** website.
- I would like to create all mentioned pages with HTML & CSS  by replacing the dummy hyperlinks.

## **Screenshots**

![Image38](https://user-images.githubusercontent.com/70098839/160259514-96374f3c-84c0-4c65-85c4-a85d9dbfaea1.PNG)

**Comment by Sakshi-1701** [comment]
Hey @VidhiBhatt01  I would love to work on this issue.
