### ISSUE TITLE
Bug : Fixing Header in FoodBlog Website

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#505]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- When scrolling down header background does not match with the theme on the **FoodBlog** Website.
- I can fix it assign it to me under GSSOC'22.

## **Screenshots**

![Image34](https://user-images.githubusercontent.com/70098839/160259712-c53856ac-2327-4b58-b6bf-6018d23808b2.PNG)

**Comment by VidhiBhatt01** [comment]
So many issues are assigned to you rn, lmk if you want to make any of these open for others to grab.

**Comment by TG922** [comment]
> So many issues are assigned to you rn, lmk if you want to make any of these open for others to grab.

Yes, sure !! You can Add open-for-all label

**Comment by TG922** [comment]
## Format I Suggest

### Note: After Being assigned from here, create a new issue using the below format (To maintain the structure)


### OFA: #(Issue No.) - Mention Issue **Helps to identify issue picked up from open-for-all issue(OFA) tab**


### Example(Create New Issue like this)

![Image53](https://user-images.githubusercontent.com/70098839/160291729-e9723435-0da9-42d9-8216-0675e3d6dfff.PNG)


## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
Let's keep it like this only as of now, will talk to PA regarding your suggestion. Also, am labeling few issues open for all. Will keep you assigned to 2 of them.

**Comment by vandana3869** [comment]
@VidhiBhatt01  i would like to work on this issue..please assign this issue to me

**Comment by VidhiBhatt01** [comment]
sure

**Comment by astha2412** [comment]
@vandana3869 Complete this issue asap!

**Comment by VidhiBhatt01** [comment]
Both the PRs were closed @vandana3869 . Take help from someone on the discord server and fix it

**Comment by TG922** [comment]
I can do it assign it to me

**Comment by astha2412** [comment]
How much time u need ?? @TG922 Complete it asap....otherwise I will close your issue.

**Comment by TG922** [comment]
I will send PR for this issue within 4-5hour

**Comment by TG922** [comment]
There is some problem with this website!!

Elements of navbar getting overlapped by **Recipes**,**Iconic Chefs Of India** section.

Just for creating a responsive header for this website, it requires redesigning the whole website. I'm closing this issue !!
