### ISSUE TITLE
Improvement : Adding fixed header in HotelWebsite

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#506]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Adding a fixed header on **HotelWebsite** which will help increase the UX of the website.

## **Screenshots**

![Image39](https://user-images.githubusercontent.com/70098839/160259863-11229e36-19c1-4bdd-be18-f7367f088460.PNG)

**Comment by kanikakaur27** [comment]
Hi. I would be keen to work on this issue.

**Comment by Sakshi-1701** [comment]
Hey @VidhiBhatt01 I would love to work on this issue. 
Please assign this to me.
