### ISSUE TITLE
PluralSight Login Page Clone

### ISSUE THREAD

**Issue by Mrjoy832** [arpit456jain/Cool-Front-End-Templates#509]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [X] Documentaion

## **Describe the bug**

- Wanted to add a clone of Pluralsight Clone using HTML, CSS
## **Possible solution**

- I will try to make this clone using HTML, CSS

## **Screenshots**

- Will be make a clone of below Website 
![image](https://user-images.githubusercontent.com/77873383/160281659-6d4cb2c2-7388-4387-bf7a-ff6f313995c6.png)

**Comment by arpit456jain** [comment]
> github

@Mrjoy832

**Comment by Mrjoy832** [comment]
> > github
> 
> @Mrjoy832 

Assign me

**Comment by arpit456jain** [comment]
@Mrjoy832 make sure u made it by yourself if we find any kind of plag we will not accept the PR
