### ISSUE TITLE
mistakes in json file

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#510]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

, is missing 335 to 563

![image](https://user-images.githubusercontent.com/55352601/160292417-8f3a568d-9fea-4d73-994d-f72ee1961896.png)

**Comment by maura-dev** [comment]
Assign to me

**Comment by arpit456jain** [comment]
sure @maura-dev but u have to make PR within 10 mins  is that ok ?

**Comment by maura-dev** [comment]
Sure

**Comment by arpit456jain** [comment]
ok go ahead @maura-dev

**Comment by arpit456jain** [comment]
@maura-dev r u making the PR ?

**Comment by rv602** [comment]
@arpit456jain assign it to me I have finished making the changes

**Comment by arpit456jain** [comment]
> @arpit456jain assign it to me I have finished making the changes

already assigned

**Comment by rv602** [comment]
@arpit456jain since I saw that this issue is urgent and is needed in 10mins I completed it. If previous assignee fails to make so let me know I will make PR

**Comment by arpit456jain** [comment]
@rv602 lets wait for 10 mins

@maura-dev do it asap

**Comment by arpit456jain** [comment]
@maura-dev  i m waiting for 5 more mins if u didn't make PR i have to assign it to @rv602

**Comment by maura-dev** [comment]
hello @arpit456jain , i've fixed it and made a pr

**Comment by arpit456jain** [comment]
checking

**Comment by arpit456jain** [comment]
@rv602 if u wish u can work on #512 
or @maura-dev
