### ISSUE TITLE
image path is missing in home page and some links are also broken

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#512]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by maura-dev** [comment]
Assign to me

**Comment by arpit456jain** [comment]
go ahead @maura-dev

**Comment by SwarupKMondal** [comment]
Please assign this to me sir

**Comment by arpit456jain** [comment]
@maura-dev r u making the PR

**Comment by arpit456jain** [comment]
@SwarupKMondal if @maura-dev didn't make PR till tomorrow it  will be assigned to u

**Comment by maura-dev** [comment]
@arpit456jain i’ll soon make the pr, it needs a lot of renaming and changes in almost all the files

**Comment by arpit456jain** [comment]
> @arpit456jain i’ll soon make the pr, it needs a lot of renaming and changes in almost all the files

@maura-dev u need to change in only style_link.json 

do not change any other file

**Comment by TG922** [comment]
done @maura-dev ?? Or should I??

I get it what's going on here **14 Projects had already images folder present** only those names required to be changed if it is not getting linked

**Comment by maura-dev** [comment]
Not really so @arpit456jain. 
The images are not showing because some have a .PNG instead of .png in their file folders and wrong capitalization in naming folders
The links are not working because of the spacing in the naming of the project links
The first one would involve touching other files so I might just probably let someone else handle it if there’s a way to do it without renaming

**Comment by TG922** [comment]
I can do it @arpit456jain, I was working on this repo for over 1 week.
Takes hardly 3 hr after being assigned to me.

I know how to deal with this issue !!

**Comment by maura-dev** [comment]
@arpit456jain  I had to tweak the script file so that I don't have to start renaming images that had .PNG instead of .png

**Comment by TG922** [comment]
Great @maura-dev is it now working properly??

**Comment by maura-dev** [comment]
Yes @TG922 check the deployment link in my pull request

**Comment by TG922** [comment]
> Yes @TG922 check the deployment link in my pull request

Yes @maura-dev you are right it works fine. How much time did it take??

**Comment by maura-dev** [comment]
Like 30 minutes. I had to revert because I had renamed the files before  I was later told not to rename them plus my laptop died😫

**Comment by TG922** [comment]
Still, it is impressive. I was literally going to rename images that had .png in place of .PNG extension 😅😅

Glad I came to know about a new method of **tweaking the script file** for such an incident.
