### ISSUE TITLE
Adding service section template.

### ISSUE THREAD

**Issue by Kumar-Ankit56** [arpit456jain/Cool-Front-End-Templates#515]
I'm a GSSoc22 contributor.  I want to add this awesome service section template for every website with an amazing hover effect.

### Idea behind the project
Like whenever we visit any website like it can be education and e-commerce website there is always a service section in the website where they show their respective service.

### How does it works?
I have designed a few containers and have set their aligned property with the grid.
Each container is like a simple UI card containing a logo for service, name, and some dummy text. Or whenever you will hover it, it will change the whole UI as compared to the original. IT is responsive as well.

please refer this.

![Screenshot (93)](https://user-images.githubusercontent.com/73521123/160339388-d204bbb5-1348-47d9-af6e-6ca59050c202.png)
![Screenshot (94)](https://user-images.githubusercontent.com/73521123/160339412-55f6a6b2-11a9-4ad4-beab-4b8a2ce12574.png)
![Screenshot (95)](https://user-images.githubusercontent.com/73521123/160339428-ede6b7ba-2479-4bfd-b561-2be5093a3bc5.png)

Thanks.

**Comment by arpit456jain** [comment]
@Kumar-Ankit56 u made it on ur own

**Comment by Kumar-Ankit56** [comment]
yeah sir, but I took layout reference online.

> @Kumar-Ankit56 u made it on ur own

**Comment by arpit456jain** [comment]
Ok make PR and mention the reference in PR
