### ISSUE TITLE
Making Whatsapp Clone fully Responsive

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [arpit456jain/Cool-Front-End-Templates#518]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

There is a folder named Whatsapp in the Cool-Front-End-Templates repo. Make that template fully responsive.

## **Screenshots**
![Screenshot (95)](https://user-images.githubusercontent.com/64724039/160458292-eae318b1-a1e2-43f8-8ffe-6c4bf67e6ff2.png)

**Comment by Sourajita21** [comment]
Can you assign me this issue. I will give my best for sure.

**Comment by DEEPIKA-SUK** [comment]
@Sourajita21 Make the PR as soon as possible.

**Comment by arpit456jain** [comment]
@Sourajita21

**Comment by astha2412** [comment]
@Sourajita21 if u r not working on this issue then plz let us know........will give chance to others!

**Comment by Sourajita21** [comment]
Yeah unfortunately I can't work in this issue.
