### ISSUE TITLE
Making web dev proj1 gym template fully responsive

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [arpit456jain/Cool-Front-End-Templates#519]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

There is a folder named web dev proj1 gym in the Cool-Front-End-Templates repo. Make that template fully responsive.

## **Screenshots**

![Screenshot (97)](https://user-images.githubusercontent.com/64724039/160460622-e4dcc587-cc20-4953-b2f1-9fedcaf3e945.png)

**Comment by primetime71** [comment]
Can you assign it to me?

**Comment by DEEPIKA-SUK** [comment]
@primetime71 Make the PR as soon as possible.
