### ISSUE TITLE
Making Space Agency template fully responsive

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [arpit456jain/Cool-Front-End-Templates#520]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

There is a folder named Space Agency template in the Cool-Front-End-Templates repo. Make that template fully responsive.

## **Screenshots**

![Screenshot (98)](https://user-images.githubusercontent.com/64724039/160462984-a1646605-1080-4cae-9d89-23a5674fd1cd.png)

**Comment by Sourajita21** [comment]
Can you assign me this task?

**Comment by astha2412** [comment]
Complete this issue @Sourajita21 asap!

**Comment by Sourajita21** [comment]
Okay sir.

**Comment by arpit456jain** [comment]
@Sourajita21

**Comment by astha2412** [comment]
@Sourajita21 ?

**Comment by Sourajita21** [comment]
Yeah unfortunately I can't work in this issue.
