### ISSUE TITLE
Improve the UI of Hotel Website

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#536]
The current UI of the Hotel Website isn't eye catchy. Enhance it, it must be fully responsive.

![image](https://user-images.githubusercontent.com/83345228/161250664-e73a7bbf-f32e-4d93-b87f-dd0353662440.png)

**Comment by srinjoy-26** [comment]
I would like to work

**Comment by Abh1shekSingh** [comment]
Can u please assign this issue to me? @VidhiBhatt01

**Comment by Abh1shekSingh** [comment]
I know UI / UX theory so i can modify it

**Comment by myhacktech** [comment]
> The current UI of the Hotel Website isn't eye catchy. Enhance it, it must be fully responsive.
> 
> ![image](https://user-images.githubusercontent.com/83345228/161250664-e73a7bbf-f32e-4d93-b87f-dd0353662440.png)

i can work for its design

**Comment by Anjuli08** [comment]
I would like to work for this issue
