### ISSUE TITLE
Improve the UI of E commerce Website

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#537]
The contact us and about us page on the eCommerce website has poor UI. Enhance it and also add a link to the home page in both of them. Both the pages must be fully responsive.

![image](https://user-images.githubusercontent.com/83345228/161251081-49afe733-0332-48f2-a0e0-3eaf1d047ab4.png)

**Comment by pujthej** [comment]
@VidhiBhatt01 Hi! Please assign this issue to me. Thank you.

**Comment by Anjuli08** [comment]
I would also like to work on this issue
