### ISSUE TITLE
Improve The UI of the Website  and Fully Responsive

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#538]
## Issue Type:

- [x] Bug Report
- [x] Feature Request

## **Describe the bug**

I would Love to Change the Whole UI UX of the Website

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Abh1shekSingh** [comment]
Hi ! Please assign this issue to me @VidhiBhatt01 @arpit456jain

**Comment by arpit456jain** [comment]
@Abh1shekSingh add the counter feature in same PR and add this is css effects in that PR also
