### ISSUE TITLE
monuments template is not completely responsive

### ISSUE THREAD

**Issue by myhacktech** [arpit456jain/Cool-Front-End-Templates#546]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- the template is not responsive at 1001*858 resolution.LINK :https://cool-front-end-templates.netlify.app/moninfo-indian%20monuments%20template/

## **Possible solution**
i can make it completely responsive
![Screenshot (272)](https://user-images.githubusercontent.com/86517958/161362721-a90172ec-4e5b-43b3-875f-ccf2177a0f0a.png)

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
We have a section for search bar like this only. It is fully responsive.

![image](https://user-images.githubusercontent.com/83345228/161371181-645389d9-65a8-4486-9a64-527dadd9fbff.png)
