### ISSUE TITLE
I want to add a Musical Website Template

### ISSUE THREAD

**Issue by kalyanikakade123** [arpit456jain/Cool-Front-End-Templates#549]
https://user-images.githubusercontent.com/86308103/161371966-96e63f91-3904-4cd9-8fa4-c5858f8c37cf.mp4

**Comment by kalyanikakade123** [comment]
Can you please assign it to me ?

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
