### ISSUE TITLE
A. Propose a new UI for Coming soon

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#550]
Redesign the coming soon page and add its SS in the comments. Whosoever has the best proposal will be assigned it.

![image](https://user-images.githubusercontent.com/83345228/161371569-1b761299-e5f8-4a5c-ad57-be69daabf7d9.png)

Make sure you do not copy-paste content from any where and it is fully responsive

**Comment by arpit456jain** [comment]
go ahead @piyusha2001 make a PR
