### ISSUE TITLE
B. Enhancing Covid 19 website

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#551]
1. Fix the image sizing
![image](https://user-images.githubusercontent.com/83345228/161371710-2edeab9b-b704-4d86-8097-8359d1c56e40.png)

2. Increase navbar font size
![image](https://user-images.githubusercontent.com/83345228/161371789-24d503f7-6fd8-4003-bf24-6cc4bacc52ba.png)

**Comment by Aritra777** [comment]
I want to work in this issue under GSSOC'22

**Comment by Sakshi-1701** [comment]
Hey @VidhiBhatt01 
If the issue is not yet solved, I'd love to work on it.
