### ISSUE TITLE
E. Redesign the footer of Maroom so that it matches with the color theme

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#554]
![image](https://user-images.githubusercontent.com/83345228/161371973-022eb893-d85a-41bf-b240-14f1508915e1.png)

**Comment by wre9-tesh** [comment]
can i be assigned this under Gssoc?

**Comment by wre9-tesh** [comment]
can i take this under gssoc?

**Comment by myhacktech** [comment]
> ![image](https://user-images.githubusercontent.com/83345228/161371973-022eb893-d85a-41bf-b240-14f1508915e1.png)

@VidhiBhatt01 i would like to work upon this issue.

**Comment by Anjuli08** [comment]
I would like to work on this issue
