### ISSUE TITLE
F. Fix the buttons

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#555]
When clicking on the navbar buttons in online grocery store website, the user is not redirected to that section of the website. Fix it

Also, either remove about us from the navbar or add a section for it.
![image](https://user-images.githubusercontent.com/83345228/161372062-5a295124-7c77-47d2-8394-10e397acbfc0.png)

**Comment by ez-sherlock** [comment]
Please assign this issue to me. Thanks :)
