### ISSUE TITLE
G. Add pages

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#556]
Add about us, contact us pages in Travel Website Template-1 

![image](https://user-images.githubusercontent.com/83345228/161372195-e98ba21e-9f4d-40fb-a395-b9cd2d3356a0.png)

**Comment by srinjoy-26** [comment]
I would like to work

**Comment by sachinkrr02** [comment]
Sir I want to work on this issue as a GSSOC'22 Contributor

**Comment by srinjoy-26** [comment]
> Sir I want to work on this issue as a GSSOC'22 Contributor

Bro Cm'on , it has been assigned to me

**Comment by arpit456jain** [comment]
@srinjoy-26 make sure you add pages with same theme and they should be responsive other wise it will be lvl1 PR

**Comment by astha2412** [comment]
@srinjoy-26 ???? Make PR Asap!

**Comment by srinjoy-26** [comment]
> @srinjoy-26 ???? Make PR Asap!

Thora tension me hu

**Comment by dheephiga** [comment]
I would like to work on this issue

**Comment by VidhiBhatt01** [comment]
@sachinkrr02

**Comment by arpit456jain** [comment]
@dheephiga r u interested ?

**Comment by dheephiga** [comment]
> @dheephiga r u interested ? 

Yes

**Comment by VidhiBhatt01** [comment]
@dheephiga you are assigned! Make the PR within 5/7 days

**Comment by BabyElias** [comment]
In case this issue is still open & needed, I am interested in taking it up :)

**Comment by DEEPIKA-SUK** [comment]
@dheephiga Make PR otherwise we will assign this issue to someone else.
