### ISSUE TITLE
Adding Finance and GST Calculator

### ISSUE THREAD

**Issue by Jagroop2000** [arpit456jain/Cool-Front-End-Templates#557]
## Issue Type:

- [ ] Feature Request

**Comment by ez-sherlock** [comment]
Here's a video demo of it:

https://user-images.githubusercontent.com/89704304/161374640-cab3c2cd-ebe9-4a40-9109-d9f4fbe54855.mp4

**Comment by VidhiBhatt01** [comment]
@Jagroop2000 are you interested on working on this or shall I assign it to @ez-sherlock ?

**Comment by VidhiBhatt01** [comment]
@ez-sherlock I think you attached the video in wrong PR

**Comment by astha2412** [comment]
@ez-sherlock ???

**Comment by astha2412** [comment]
@Jagroop2000 Complete your issue asap otherwise I will close this issue!
