### ISSUE TITLE
StudyX website is not responsive at all.

### ISSUE THREAD

**Issue by ez-sherlock** [arpit456jain/Cool-Front-End-Templates#558]
[StudyX Website](https://cool-front-end-templates.netlify.app/online%20tutorial%20website%20template/#) only looks good on the big screens (Screen sizes bigger than 1366*766 px). It looks very bad (unresponsive) for laptops, tablets, and mobile screens.

**Comment by VidhiBhatt01** [comment]
@ez-sherlock add the video here

**Comment by ez-sherlock** [comment]
Okay

**Comment by astha2412** [comment]
@ez-sherlock Complete this issue asap!

**Comment by aaryahjolia** [comment]
Can I work on this under GSSoC ?

**Comment by arpit456jain** [comment]
@ez-sherlock updates ?

**Comment by VidhiBhatt01** [comment]
@aaryahjolia assigned to you
