### ISSUE TITLE
I. Add a blog page

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#562]
Project : Welcome to Lucknow

![image](https://user-images.githubusercontent.com/83345228/161390820-d0c8878e-9835-49bf-9d3f-6c375c73f5a2.png)

Tasks:
1. Add hover effects in Navbar.
2. Add a Blog page.
3. Rename the document title from "First Website" to "Welcome to Lucknow"

**Comment by Abh1shekSingh** [comment]
Please Assign this issue to @VidhiBhatt01

**Comment by astha2412** [comment]
@Abh1shekSingh ???? Complete this issue Asap!

**Comment by Abh1shekSingh** [comment]
In progress, vidhi knows. I am experimenting something
