### ISSUE TITLE
J. Make the Yoga Template Website fully responsive.

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#563]
![image](https://user-images.githubusercontent.com/83345228/161390939-baca88de-0d63-4be3-a468-d3d1f79328d1.png)

**Comment by Abh1shekSingh** [comment]
Please assign this issue to me maam @VidhiBhatt01

**Comment by Vanshika7902** [comment]
I like to work on this issue .Please assign it to me.

**Comment by Abh1shekSingh** [comment]
It's is based first come first serve.  So I have already asked.

**Comment by pujthej** [comment]
@VidhiBhatt01 hi! this issue is already open. It is #492 and I had requested to work on it few days back.
