### ISSUE TITLE
K. Fix the text Alignment

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#564]
Project: Newsletter

![image](https://user-images.githubusercontent.com/83345228/161391021-74fc428c-f211-4c07-9b02-5e4429a1c4be.png)

Tasks:
1. As seen in the image, the text is getting cut, fix that.
2. Rename document title from "Document" to "Newsletter".

**Comment by Anirban-1490** [comment]
assign me this

**Comment by Vanshika7902** [comment]
I like to work on this issue .Please assign it to me.

**Comment by sachinkrr02** [comment]
sir i would like work on this issue
