### ISSUE TITLE
L. Enhance Rural Art Template

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#565]
1.  Fix horizontal scroll

![image](https://user-images.githubusercontent.com/83345228/161391137-492dd5ec-a468-4b36-bd5f-809af50e5709.png)

2. Make the website fully responsive

![image](https://user-images.githubusercontent.com/83345228/161391175-b901c2df-b9e0-445f-b2db-b42b5d56cf30.png)

3. Give a suitable document title

**Comment by Anirban-1490** [comment]
assign me this too
