### ISSUE TITLE
Adding Typing Master Game Clone

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#572]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Adding Typing Master Game Clone using HTML, CSS, JS.

## **Screenshots**

![Image67](https://user-images.githubusercontent.com/70098839/161413784-bc17b075-112c-4adf-8f49-18a2ac82c84d.PNG)

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects for a certain period. check #announcements under project channels on discord for further guidelines.
