### ISSUE TITLE
Tesla Clone Using React

### ISSUE THREAD

**Issue by nithu2109** [arpit456jain/Cool-Front-End-Templates#574]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- I Would like to add Tesla front end clone

## **Screenshots**

![image](https://user-images.githubusercontent.com/67360225/161416728-81963dae-e6d9-43c8-b8ae-c688329d5b6b.png)

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects for a certain period. check #announcements under project channels on discord for further guidelines.

Plus, react projects are not accepted as of now.
