### ISSUE TITLE
want to contribute the frontend of a blog website.

### ISSUE THREAD

**Issue by TadrupDas** [arpit456jain/Cool-Front-End-Templates#576]
@arpit456jain  I have already finished the frontend part of the blog website. can i contribute here?

**Comment by VidhiBhatt01** [comment]
@TadrupDas elaborate more on what you are talking about

**Comment by astha2412** [comment]
@arpit456jain ??

**Comment by arpit456jain** [comment]
@TadrupDas np just make PR we only need front end not the backend

**Comment by VidhiBhatt01** [comment]
@TadrupDas
