### ISSUE TITLE
Show all cards by clicking on load more

### ISSUE THREAD

**Issue by samipak458** [arpit456jain/Cool-Front-End-Templates#581]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Showing all the card at the same time is not looking good according to me. I think adding pagination or load more button make website UI more better. I am GSSOC'22 participant kindly assign this issue to me.

## **Possible solution**
I would add load more button. When you click on the button all the cards will be shown.

## **Screenshots**

![LoadMore](https://user-images.githubusercontent.com/52650290/161537730-2e6839f9-6676-4faa-8b63-0519c36d3e25.jpeg)

**Comment by samipak458** [comment]
@arpit456jain kindly assign this issue to me.

**Comment by arpit456jain** [comment]
@samipak458 some one is working on this we will let you know if she fails
