### ISSUE TITLE
Crypto Website Template

### ISSUE THREAD

**Issue by dsasaank-369** [arpit456jain/Cool-Front-End-Templates#591]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Possible solution**

This is a template for a Crypto-based website. I have used HTML,CSS,JS etc. This can be used as a template.

## **Screenshots**
![image](https://user-images.githubusercontent.com/80057285/161955185-9bf43c53-0fac-4246-a17d-8cf1f452171e.png)

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
