### ISSUE TITLE
Grocery Shopping List Maintainer

### ISSUE THREAD

**Issue by AnIkeT126** [arpit456jain/Cool-Front-End-Templates#592]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

This is a cool app using which you can keep a list of items you need to buy, you just have to add the items needed. You can also delete the item/items which are not required. 

- [x] GSSoC Contributor

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by AnIkeT126** [comment]
@arpit456jain please assign this issue to me under GSSoC and if possible add a level label.

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
