### ISSUE TITLE
UI of the portfolio template can be improved

### ISSUE THREAD

**Issue by myhacktech** [arpit456jain/Cool-Front-End-Templates#594]
## Issue Type:
link to the portfolio: https://cool-front-end-templates.netlify.app/simple%20portfolio%20template/

- [x ] Feature Request

## **Describe the bug**

In the service section, the picture does not fit in the frame.

## **Possible solution**

i can design it properly, so that picture fits in it .

## **Screenshots**

![Screenshot (282)](https://user-images.githubusercontent.com/86517958/161983688-37d32aeb-5bfd-41d8-9515-2ab1036f4e2a.png)

**Comment by astha2412** [comment]
@myhacktech Complete this issue asap!

**Comment by myhacktech** [comment]
> @myhacktech Complete this issue asap!
Ok
