### ISSUE TITLE
Fix the extra space and templates are not center 

### ISSUE THREAD

**Issue by codingkush** [arpit456jain/Cool-Front-End-Templates#597]
## Issue Type:

Extra space left side of website 

- [ ] 

## **Describe the bug**

I visited this website and  then i found the extra space in left side of whole website and the  templates are not center.....

![Screenshot_20220406-205355~2](https://user-images.githubusercontent.com/78756312/162012910-b8e508d8-4072-4ac5-a1ec-abbf0491cd18.png)

**Comment by codingkush** [comment]
I'm GSsoc 22 contributer and i want to work on this issue under GSsoc 22...plz assign it to me

**Comment by VidhiBhatt01** [comment]
@arpit456jain

**Comment by ishashukla183** [comment]
i would like to work on this issue

**Comment by codingkush** [comment]
Me too ...

**Comment by arpit456jain** [comment]
go ahead @codingkush

**Comment by codingkush** [comment]
Ok..

**Comment by codingkush** [comment]
How many templates wil  be show in tablet mode...??  Right now only one templates is showing...

**Comment by codingkush** [comment]
Pls tell me...

**Comment by arpit456jain** [comment]
> How many templates wil be show in tablet mode...?? Right now only one templates is showing...

2 will be good
