### ISSUE TITLE
Clone this website 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#598]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

Clone this website https://supervise.ly/

but for now just clone this page 

https://supervise.ly/lidar-3d-cloud/

![screencapture-supervise-ly-lidar-3d-cloud-2022-04-06-23_54_40](https://user-images.githubusercontent.com/55352601/162042872-403aeefb-39ec-4e50-9a51-241345dd9d78.png)

**Comment by dewanshiPaul** [comment]
We have to do frontend only?

**Comment by arpit456jain** [comment]
yes @dewanshiPaul

**Comment by dewanshiPaul** [comment]
What is the deadline?

**Comment by arpit456jain** [comment]
@dewanshiPaul r u interested ?

**Comment by dewanshiPaul** [comment]
I am interested but this tight deadline because tomorrow i have offline classes upto 5:30pm. If you extend deadline, then it is possible

**Comment by arpit456jain** [comment]
ok @dewanshiPaul work on it make it asap

**Comment by dewanshiPaul** [comment]
Oo i will try to complete it asap

**Comment by maura-dev** [comment]
Interested

**Comment by arpit456jain** [comment]
@maura-dev go ahead and make PR before tomorrow evening.

**Comment by Sukriti-m** [comment]
@arpit456jain I am interested. Can it be assigned to me as well?

**Comment by anirudh357** [comment]
Interested

**Comment by arpit456jain** [comment]
> Interested

@anirudh357 can you do it before end of the day?

**Comment by anirudh357** [comment]
> > Interested
> 
> @anirudh357 can you do it before end of the day?

Can I do till tomorrow, like till tomorrow morning.

**Comment by arpit456jain** [comment]
@anirudh357 yes u can go ahead

**Comment by maura-dev** [comment]
Same, just started

**Comment by arpit456jain** [comment]
@maura-dev @dewanshiPaul @anirudh357 make PR asap the one who makes PR first can work on other pages as well

**Comment by arpit456jain** [comment]
@dewanshiPaul @anirudh357 @maura-dev any update ?

**Comment by dewanshiPaul** [comment]
Completed with nav bar

**Comment by dewanshiPaul** [comment]
Proceeding further

**Comment by anirudh357** [comment]
Made navbar and body section @arpit456jain

**Comment by GaganpreetKaurKalsi** [comment]
Hey! I am interested on working on this issue. 
Let me know if you still need this page to be build up or if any other pages to work on.
Thanks!

**Comment by arpit456jain** [comment]
> Hey! I am interested on working on this issue. Let me know if you still need this page to be build up or if any other pages to work on. Thanks!

Yes @GaganpreetKaurKalsi go ahead

**Comment by GaganpreetKaurKalsi** [comment]
Please share the url once which you want me to clone. The one mentioned in the description is broken and I see many changes have taken place in the UI of the site.

**Comment by dewanshiPaul** [comment]
@arpit456jain  i have made half of the website clone and now the UI of the website is changed what should i do now?

**Comment by ishashukla183** [comment]
i would like to work on this issue

**Comment by arpit456jain** [comment]
> @arpit456jain i have made half of the website clone and now the UI of the website is changed what should i do now?

@dewanshiPaul just continue with the previous one

**Comment by arpit456jain** [comment]
@GaganpreetKaurKalsi @ishashukla183 i have another page for u guys

**Comment by arpit456jain** [comment]
@dewanshiPaul

**Comment by dewanshiPaul** [comment]
Ok i will try to complete it soon. Exams are going

**Comment by arpit456jain** [comment]
@dewanshiPaul make PR asap
