### ISSUE TITLE
Color code getter for CSS colors

### ISSUE THREAD

**Issue by YalfamIamShaon** [arpit456jain/Cool-Front-End-Templates#601]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

 I'd like to add one of my web project called "Color Code Getter for CSS." This project makes it simple for users to find "Hexcode" for any colouring, so we don't have to waste time looking for that in Web pages. Here's a video of my project in action.

## **Screenshots**

https://user-images.githubusercontent.com/84259582/162122054-5c05d7d2-0068-4fac-bf7d-118ac2ed8005.mp4

**Comment by YalfamIamShaon** [comment]
hello @arpit456jain , if you like this project can you assign it to me?

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
