### ISSUE TITLE
food template is not responsive and items are not aligned properly

### ISSUE THREAD

**Issue by myhacktech** [arpit456jain/Cool-Front-End-Templates#602]
## Issue Type:
link to the template:https://cool-front-end-templates.netlify.app/food%20website%20template/
- [x] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

template is not responsive and form inputs boxes are not aligned properly

## **Possible solution**
can be made responsive
![Screenshot (284)](https://user-images.githubusercontent.com/86517958/162126768-5bb2155a-dd6c-4750-bfe4-b0acc57fe3da.png)
![Screenshot (283)](https://user-images.githubusercontent.com/86517958/162126802-2fe4f21d-d4ec-4f8a-8fad-0653ee064049.png)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ishashukla183** [comment]
i would like to work on this issue

**Comment by myhacktech** [comment]
> i would like to work on this issue

I am working on this issue,as soon my current PR gets merged,i 'll create PR for this
