### ISSUE TITLE
Making Tourism-Portal Fully Responsive

### ISSUE THREAD

**Issue by Vanshika7902** [arpit456jain/Cool-Front-End-Templates#603]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Tourism Portal Template is not Responsive.

## **Possible solution**

- Can be made Responsive.

## **Screenshots**

-  
![Screenshot (97)](https://user-images.githubusercontent.com/92636041/162163000-48d49f6e-0628-4d01-bc55-1ebade5351bf.png)

**Comment by arpit456jain** [comment]
@Vanshika7902 make PR within 3 days

**Comment by astha2412** [comment]
@Vanshika7902 ???
