### ISSUE TITLE
Adding Links for GSSoc'22, hacktoberfest 2021, DevIncept and finally  the Demo video link for this repo

### ISSUE THREAD

**Issue by muhammadgalhoum** [arpit456jain/Cool-Front-End-Templates#606]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## I will do the following changes 

- I will add the link for GSSoc'22
- I will add the link for hacktober fest 2021
- I will add the link for DevIncept
- I will add the link for the Demo video link for this repo

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by muhammadgalhoum** [comment]
**Please assign this issue to me @arpit456jain**

**Comment by VidhiBhatt01** [comment]
@arpit456jain

**Comment by muhammadgalhoum** [comment]
**Can you assign this to me please @arpit456jain @VidhiBhatt01 **

**Comment by muhammadgalhoum** [comment]
### Please can anyone assign this issue to me and I will solve it asap @DEEPALI-SUK @DEEPIKA-SUK @astha2412 @VidhiBhatt01 @arpit456jain 
### Thanks in advanced

**Comment by ishashukla183** [comment]
i would like to work on this issue
