### ISSUE TITLE
Improve UI of Hotel Website

### ISSUE THREAD

**Issue by Anish-Parkhi** [arpit456jain/Cool-Front-End-Templates#608]
## **Description**
 
Improve the UI of Hotel Website. The search bars on the top dosen't looks good. The search bars should be short and they should fit in a single line only 

## **Screenshots**

![Screenshot (172)](https://user-images.githubusercontent.com/93964690/162251807-460fd26f-407d-4e44-a952-820a29525bb0.png)

**Comment by arpit456jain** [comment]
@Anish-Parkhi

**Comment by astha2412** [comment]
@Anish-Parkhi Complete your issue asap!!!

**Comment by Abhilasha-Jairath** [comment]
Hey !! I want to work on this under GSSOC2022. I can improve the UI few days. Can you assign it to me !?

**Comment by astha2412** [comment]
> Hey !! I want to work on this under GSSOC2022. I can improve the UI few days. Can you assign it to me !?

Make PR ASAP!

**Comment by Abhilasha-Jairath** [comment]
I have cloned the website , but I couldn't find the Hotel website , can you direct me to it .

**Comment by DEEPIKA-SUK** [comment]
@astha2412 

> I have cloned the website , but I couldn't find the Hotel website , can you direct me to it .
