### ISSUE TITLE
UI of Healthcare Technology Website 

### ISSUE THREAD

**Issue by mohammadshaad** [arpit456jain/Cool-Front-End-Templates#610]
I want to make the UI of a healthcare technology website.
I am a GSSoC'22 contributor and I want to work on this issue kindly assign it to me

**Comment by arpit456jain** [comment]
@mohammadshaad

**Comment by mohammadshaad** [comment]
Yes I am working on this issue

**Comment by astha2412** [comment]
@mohammadshaad Make PR fast!
