### ISSUE TITLE
I want to add card and carousel effect in Chinese Restaurant.

### ISSUE THREAD

**Issue by ak232001** [arpit456jain/Cool-Front-End-Templates#616]
## Issue Type:

- [ ] Feature Request

## **Description**

- I want to add Card effect in Menu Section And Carousel Effect in Service section of Chinese Resturant Template.

 Hey @VidhiBhatt01 , i want to add this beautiful effect . Please assigned me this. 

## **Screenshots**
![img2](https://user-images.githubusercontent.com/93785942/162588416-5915302f-4a3c-4857-8739-8af05a5569eb.PNG)

![Capture](https://user-images.githubusercontent.com/93785942/162588393-c1dc6af9-de45-469c-ac84-db47beb6238d.PNG)

**Comment by ak232001** [comment]
Please Assign me this issue @VidhiBhatt01

**Comment by arpit456jain** [comment]
@ak232001

**Comment by VidhiBhatt01** [comment]
@ak232001 final call, are you working on it?
