### ISSUE TITLE
I want to make online grocery store fully responsive

### ISSUE THREAD

**Issue by ak232001** [arpit456jain/Cool-Front-End-Templates#621]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request

## **Describe the bug**

- Online Grocery Store Project is not fully responsive.
 
## **Possible solution**

- Can be made responsive

## **Screenshots**
![Capture1](https://user-images.githubusercontent.com/93785942/162619919-2134b008-37c7-4972-b86d-8cc7f6f4dffd.PNG)

- If applicable, add
![Capture2](https://user-images.githubusercontent.com/93785942/162619923-4d3b0e6d-2bd8-4fa5-884c-8f03426bed14.PNG)
 screenshots to help explain your problem.

Hey @VidhiBhatt01 assign me this please.I want to work on it.

**Comment by arpit456jain** [comment]
@ak232001 we can't accept this it will contain under plag its the website made by code with harry and its already present
