### ISSUE TITLE
Projects open in same tab as that of homepage

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [arpit456jain/Cool-Front-End-Templates#629]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Right now when we click on a project it opens up in the same tab which is quite hard for the user, If I am checking projects then there is a lot of going back and forth the same tab.

## **Possible solution**

- We can make the projects open up in a new tab everytime instead of opening up in the same as that of homepage.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by GaganpreetKaurKalsi** [comment]
Please assign me the issue

**Comment by DEEPIKA-SUK** [comment]
@GaganpreetKaurKalsi try to make the PR by tomorrow.
