### ISSUE TITLE
Zomato Clone UI improvements

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [arpit456jain/Cool-Front-End-Templates#630]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- The buttons are too large
![image](https://user-images.githubusercontent.com/54144759/162831314-ce2bbd0d-34a1-48ce-ba92-4e79d0f55e33.png)

- The input tag requires some padding and styling
![image](https://user-images.githubusercontent.com/54144759/162831503-5fe19696-619d-45ad-8a83-b45c7aa0ca96.png)

- Footer links font-size and icon are too large
![image](https://user-images.githubusercontent.com/54144759/162831628-03ce766e-6891-4e10-8f69-9fddc94407ed.png)
 

## **Possible solution**

- Will reduce the size of the button
- add padding to the input field and remove outline on focus event for input element
- Will reduce the font-size and size of icon.
- Will check for mobile view as well for any discrepancy or UI improvements required.

## **Screenshots**

-  Already attached above.

**Comment by GaganpreetKaurKalsi** [comment]
Please assign me the issue. 
Thanks!

**Comment by ishashukla183** [comment]
I would like to work on this issue
