### ISSUE TITLE
change navbar opacity in yoga template 2

### ISSUE THREAD

**Issue by wre9-tesh** [arpit456jain/Cool-Front-End-Templates#639]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

i want to change the opacity so that text doesnt overlap.
## **Screenshots**

![Screenshot 2022-04-13 154126](https://user-images.githubusercontent.com/96977189/163156192-a375d3ff-dbb5-4828-93ad-00f2c11546c1.jpg)

**Comment by wre9-tesh** [comment]
/assign 
i am a gssoc participant and want to work on this

**Comment by DEEPIKA-SUK** [comment]
@wre9-tesh make the PR by today.

**Comment by wre9-tesh** [comment]
ok
