### ISSUE TITLE
Architect Website

### ISSUE THREAD

**Issue by rithik-sharma** [arpit456jain/Cool-Front-End-Templates#641]
## Issue Type:

- [ ] Bug Report
- [ yes] Feature Request
- [yes ] Documentaion

## **Describe the bug**

- It is an Amazing Architect Website with some amazing features....

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DEEPIKA-SUK** [comment]
@rithik-sharma Kindly fill the description properly.
