### ISSUE TITLE
Making E-commerce shopping website fully responsive

### ISSUE THREAD

**Issue by Sakshi-1701** [arpit456jain/Cool-Front-End-Templates#642]
## Issue Type:

- [x] Bug Report

## **Describe the bug**

1. In the mobile view, extra white spaces are there in the right corner.
2. The navbar isn't fully responsive as it leaves space on the top.
3. The footer needs to be made responsive and fixing the overflowing text.

## **Screenshots**

![issue1](https://user-images.githubusercontent.com/84696772/163316385-cee894d4-ef5a-4f8f-a742-1319ad2dbd92.PNG)
![issue2](https://user-images.githubusercontent.com/84696772/163316405-c95d5068-df34-4b22-9be0-7ea91abdaec4.PNG)

**Comment by pushpanjali-10** [comment]
I want to work on this issue, and can work on it on an urgent basis, can you please assign it to me??
