### ISSUE TITLE
Bakery Website

### ISSUE THREAD

**Issue by stutimohta20** [arpit456jain/Cool-Front-End-Templates#649]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- Front End Website For a Homebaker

## **Possible solution**

- Website using HTML,CSS and JS

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by stutimohta20** [comment]
Please assign this to me

**Comment by pushpanjali-10** [comment]
I want to work on this issue, and can work on it on an urgent basis, can you please assign it to me??

**Comment by stutimohta20** [comment]
@arpit456jain Please assign this to me.

**Comment by arpit456jain** [comment]
@pushpanjali-10 check #655  its urgent

**Comment by arpit456jain** [comment]
@stutimohta20 go ahead but  the template should be responsive

**Comment by stutimohta20** [comment]
Ok Thanks :)
