### ISSUE TITLE
Clone this webpage 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Cool-Front-End-Templates#655]
url : https://data.neonscience.org/data-products/explore

![image](https://user-images.githubusercontent.com/55352601/163702387-aecd1c69-1ce8-4d7d-afd9-a7543e228bfc.png)

**Comment by arpit456jain** [comment]
leave the navbar just clone the rest of the web page

**Comment by pushpanjali-10** [comment]
Can you assign to me ?

**Comment by arpit456jain** [comment]
Go ahead @pushpanjali-10

**Comment by arpit456jain** [comment]
@pushpanjali-10

**Comment by pushpanjali-10** [comment]
almost done.

**Comment by pushpanjali-10** [comment]
it is giving some error.

**Comment by pushpanjali-10** [comment]
It is giving some error and taking time

**Comment by SupriyaGembali** [comment]
@arpit456jain Please assign this issue to me, I can make it by today itself

**Comment by arpit456jain** [comment]
@pushpanjali-10 complete it by tomorrow otherwise it will be assigned to @SupriyaGembali

**Comment by arpit456jain** [comment]
@SupriyaGembali go ahead

**Comment by SupriyaGembali** [comment]
@arpit456jain I have made it free of errors and limited the page to few display items with simple functionality. Please review
