### ISSUE TITLE
Blogging website

### ISSUE THREAD

**Issue by sainiteshb** [arpit456jain/Cool-Front-End-Templates#663]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- Blogging website to let blogger display their blogs to the users.

## **Possible solution**

- A responsive website using html,css and js.
- Assign me ,so i can continue developing the website.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by sainiteshb** [comment]
Please assign me this ,so i can continue developing the website, thank you.

**Comment by arpit456jain** [comment]
> Hello there!👋, @sainiteshb Welcome to the Cool-Front-End_Templates project!🚀⚡Thank you and congrats🎉 for opening issue in this project. Please make sure not to start working on the issue, unless you get assigned to it.😄 currently we are not accepting new templates sorry for inconvenience u can checkout the issues which are opend or u can create a issue for improving any existing template

.
