### ISSUE TITLE
Adding New Contact Page in Ecommerce shopping website

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Cool-Front-End-Templates#668]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Contact us page on the eCommerce shopping website is not well.

## **Possible solution**

- I would like to Add New Contact Page on the eCommerce shopping website

## **Screenshots**

![Image31](https://user-images.githubusercontent.com/70098839/164314441-e6cf4af9-1ee8-4ee6-bb0a-0621c8050e64.PNG)

**Comment by arpit456jain** [comment]
@TG922 first complete the issues assigned to u

**Comment by TG922** [comment]
Ok @arpit456jain
