### ISSUE TITLE
Adobe Photoshop Website Clone

### ISSUE THREAD

**Issue by eswarbhageerath** [arpit456jain/Cool-Front-End-Templates#673]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Clone Of Adobe Photoshop Website

The idea behind this project
This is a very mini project which looks similar to the famous Photo editing website Adobe Photoshop.

Please refer to the images below:
![ss1](https://user-images.githubusercontent.com/76146796/164766671-e6d7a864-77d6-448c-af89-a68fbdc6d3e2.png)
![ss2](https://user-images.githubusercontent.com/76146796/164766674-b33b4352-cd47-4772-8f67-2f12458e97ca.png)
![ss3](https://user-images.githubusercontent.com/76146796/164766676-57e7b80a-af0e-4a4d-8856-48f271424ff0.png)
![ss4](https://user-images.githubusercontent.com/76146796/164766678-28d3e80e-2184-4891-b228-de2e7faa608a.png)
![ss5](https://user-images.githubusercontent.com/76146796/164766681-2bd72401-aa5d-4350-a720-ff840745e1e7.png)
![ss6](https://user-images.githubusercontent.com/76146796/164766683-9793840e-6a79-4463-a8da-0e017fabbe32.png)

**Comment by eswarbhageerath** [comment]
@arpit456jain Please assign this issue to me

**Comment by arpit456jain** [comment]
@eswarbhageerath make PR within 3 days
