### ISSUE TITLE
Correct the alignment 

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [arpit456jain/Cool-Front-End-Templates#677]
## Issue Type:

- [1] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

The alignment of the simple dark login form is not perfect.I want to give proper alignment in the input field and label.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![alignment](https://user-images.githubusercontent.com/89297894/164883316-b21d1b7c-1b54-4382-b319-73c261ac96ff.png)

**Comment by AsmaIbrahimButt** [comment]
@arpit456jain Kindly assign me this issue.

**Comment by DEEPIKA-SUK** [comment]
@AsmaIbrahimButt make PR by tomorrow otherwise we will close this issue.

**Comment by AsmaIbrahimButt** [comment]
@DEEPIKA-SUK I checked someone is already update it :).There is no issue.
