### ISSUE TITLE
fashion website

### ISSUE THREAD

**Issue by shubhra-g** [arpit456jain/Cool-Front-End-Templates#678]
An interactive shopping website using HTML , CSS and javascript

**Comment by shubhra-g** [comment]
Kindly assign me to this issue

**Comment by DEEPIKA-SUK** [comment]
@shubhra-g Make pr by tomorrow otherwise we will close this issue.

**Comment by DEEPIKA-SUK** [comment]
@shubhra-g Make it responsive for all width sizes.
![Screenshot (123)](https://user-images.githubusercontent.com/64724039/166683868-249564e8-13ca-4ab8-b1ab-f0237009eb2f.png)
![Screenshot (124)](https://user-images.githubusercontent.com/64724039/166683910-1f59ea97-d456-44d0-be06-9065d85914a0.png)
