### ISSUE TITLE
Wanted to add navigation bar in glassmorphic profile card

### ISSUE THREAD

**Issue by Kamleshseervi** [arpit456jain/Cool-Front-End-Templates#679]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Kamleshseervi** [comment]
navigation bar sucessfully

**Comment by DEEPIKA-SUK** [comment]
> navigation bar sucessfully @arpit456jain

@Kamleshseervi Where is the PR??

**Comment by Kamleshseervi** [comment]
actually i am new to github and don't know 
how to add pr and all can you please guide me
