### ISSUE TITLE
Add Gym Website template

### ISSUE THREAD

**Issue by nouraan-ahmed** [arpit456jain/Cool-Front-End-Templates#682]
## Issue Type:
-  Feature Request

## **Describe the project**
An interactive Gym website using HTML , CSS and javascript

**Comment by nouraan-ahmed** [comment]
@VidhiBhatt01 Please assign me to this task

**Comment by VidhiBhatt01** [comment]
You can not raise a PR before the issue is assigned. Be careful from next time else the PR will be marked as invalid

**Comment by DEEPIKA-SUK** [comment]
@nouraan-ahmed make pr by today.
