### ISSUE TITLE
Add Travel Agency Website Template

### ISSUE THREAD

**Issue by nouraan-ahmed** [arpit456jain/Cool-Front-End-Templates#684]
## Issue Type:

- [x] Feature Request

## **Describe the project**

I have created An interactive Travel Agency website using HTML , CSS and javascript

**Comment by nouraan-ahmed** [comment]
please assign me to this task
@arpit456jain @ankitapuri @VidhiBhatt01 @astha2412

**Comment by VidhiBhatt01** [comment]
We already have similar templates
