### ISSUE TITLE
Guardian Gym Project Changes

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#688]
## Issue Type:

- [x] Bug Report
- [x] Feature Request

## **Describe the bug**

I will Do the Following Chnages
1. Color Scheme 
2. Font
3. New UI 
4. Use of Attractive images to showcase our facility
5. More attractive UI design
6. I have some design in my mind which i would love to code

**Comment by Abh1shekSingh** [comment]
PLease Assign the Task

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @arpit456jain Please Assign the Task

**Comment by arpit456jain** [comment]
which guardian gym project share the link

**Comment by Abh1shekSingh** [comment]
https://cool-front-end-templates.netlify.app/gym%20website/

**Comment by Abh1shekSingh** [comment]
The above one @arpit456jain

**Comment by VidhiBhatt01** [comment]
One pending PR rn of this website. Wait till it get's merged. @Abh1shekSingh

**Comment by Abh1shekSingh** [comment]
Okay !
