### ISSUE TITLE
want to create a music website 

### ISSUE THREAD

**Issue by Kamleshseervi** [arpit456jain/Cool-Front-End-Templates#689]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
We already have similar projects
