### ISSUE TITLE
the travel website is not responsive

### ISSUE THREAD

**Issue by myhacktech** [arpit456jain/Cool-Front-End-Templates#696]
## Issue Type:
link of travel website:https://cool-front-end-templates.netlify.app/travel%20website%20template-1/
- [ ] Feature Request

## **Describe the bug**

background image does not completely fits to the window on changing resolution.

## **Possible solution**
can be made responsive
![Screenshot (327)](https://user-images.githubusercontent.com/86517958/165140815-06f22681-2a36-4da8-8c60-5d2154f98a01.png)

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DEEPIKA-SUK** [comment]
@myhacktech make pr by tomorrow or we will close this issue.

**Comment by myhacktech** [comment]
> @myhacktech make pr by tomorrow or we will close this issue.

ok
