### ISSUE TITLE
Adding favicon in other pages

### ISSUE THREAD

**Issue by aaryahjolia** [arpit456jain/Cool-Front-End-Templates#709]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

The favicon is there in main page (cool front end templates page) but not in other pages, So I want to add the favicon in all the pages of website so it will look good.

## **Possible solution**

Adding favicon to all the html pages so the website will look more good.

## **Screenshots**

![GSSoC](https://user-images.githubusercontent.com/82600388/165981680-e672f2aa-b456-40e8-8731-ce6cad677d81.png)

**Comment by DEEPIKA-SUK** [comment]
@aaryahjolia try to complete it in 2 days.

**Comment by aaryahjolia** [comment]
As I'll have to work on sibling repo (Amazing-Css-efffects and Amazing-JS-projects), Please assign me the issue opened in respective repo, the links for which are below : 
[https://github.com/arpit456jain/Amazing-Js-Projects/issues/595](https://github.com/arpit456jain/Amazing-Js-Projects/issues/595)
[https://github.com/arpit456jain/Amazing-Css-Effects/issues/597](https://github.com/arpit456jain/Amazing-Css-Effects/issues/597)

Once assigned, You can close this issue.
