### ISSUE TITLE
Adding Valorant Website Clone

### ISSUE THREAD

**Issue by MonarchGitHub** [arpit456jain/Cool-Front-End-Templates#712]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

I want to clone the **Valorant website**, the website has lots of cool animations and it will be a good learning resource for upcoming web developers who will explore the code. You can take a look at their website [HERE](https://playvalorant.com/en-us/).

## **Screenshots**

![image](https://user-images.githubusercontent.com/74449136/159151750-bb843d0b-7a2c-4674-91c3-c2f150c91c67.png)
***************************
![image](https://user-images.githubusercontent.com/74449136/159151769-8b8ce1cb-22de-4931-a008-6a9ccaf010de.png)

**Comment by MonarchGitHub** [comment]
Kindly assign this issue to me under Gssoc22.

**Comment by DEEPIKA-SUK** [comment]
@MonarchGitHub do it within 2 days.

**Comment by DEEPIKA-SUK** [comment]
> > @MonarchGitHub do it within 2 days.
> 
> Okay sure, kindly add level tag to the issue @DEEPIKA-SUK

@arpit456jain

**Comment by DEEPIKA-SUK** [comment]
@MonarchGitHub First make the PR.

**Comment by arpit456jain** [comment]
lvl will be given on the basis of work

**Comment by arpit456jain** [comment]
@MonarchGitHub make PR asap

**Comment by MonarchGitHub** [comment]
> @MonarchGitHub make PR asap

I'm on it, will do it by EOD max 👍

**Comment by DEEPIKA-SUK** [comment]
@MonarchGitHub any update?

**Comment by MonarchGitHub** [comment]
I had some unexpected project to attend to, I'll make the PR today positively

**Comment by astha2412** [comment]
@MonarchGitHub ?? Complete it today itself!!!!!

**Comment by astha2412** [comment]
Ok
