### ISSUE TITLE
Slider to Change the Time

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Cool-Front-End-Templates#730]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![preview](https://user-images.githubusercontent.com/72241207/166171962-0dbefce0-44b1-4f4c-ad68-936291f5a16f.gif)

**Comment by arpit456jain** [comment]
add this is in amazing css effects
