### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Cool-Front-End-Templates#731]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A Scrollable calendar

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- ![image](https://user-images.githubusercontent.com/72241207/166173004-5e1dc6f0-633b-4c7f-a2b4-d46967a7adfa.png)

**Comment by arpit456jain** [comment]
add this in amazing css effects
