### ISSUE TITLE
A single paged food delivery website UI fully responsive

### ISSUE THREAD

**Issue by aaryahjolia** [arpit456jain/Cool-Front-End-Templates#742]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

I would like to add a fully responsive single page food delivery website with a simple UI.

## **Screenshots**

![image](https://user-images.githubusercontent.com/82600388/166425060-1fb9703f-73fa-4d15-8726-27504ad7793d.png)

**Comment by VidhiBhatt01** [comment]
We already have something similar
