### ISSUE TITLE
Pure CSS Battery Layout

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Cool-Front-End-Templates#746]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A Pure CSS Battery Layout

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- ![image](https://user-images.githubusercontent.com/72241207/166504102-b0c4a2c6-f771-45e4-8e7e-810b3c572f32.png)

**Comment by VidhiBhatt01** [comment]
Don't you think this will be more suitable in CSS effects repo?

**Comment by DragonUncaged** [comment]
okay
