### ISSUE TITLE
Recipe Website

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Cool-Front-End-Templates#758]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/72241207/166834522-2431ecc3-247b-44a2-8cf6-5a24df882891.png)

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged add more description of the issue.
