### ISSUE TITLE
Portfolio Website Template

### ISSUE THREAD

**Issue by SarthakSKumar** [arpit456jain/Cool-Front-End-Templates#762]
Hey there. 
I would like to add a Personal Portfolio Website Template to the Repo, with features like Dark/Light Mode, Swipers, Etc. I will be doing this using HTML, CSS and JS.

**Comment by DEEPIKA-SUK** [comment]
@SarthakSKumar Portfolio template project already exists.  You can do changes in that.

**Comment by SarthakSKumar** [comment]
Thank you for your reply. The one I was planning to add was entirely different from the one already in the repo. It is a single-page website, with editable sections, smooth transitions, dark/light modes, and a more appealing UI. Please let me know if I can work on this. Thanks again😅 @DEEPIKA-SUK @arpit456jain
