### ISSUE TITLE
NFT Viewer

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Cool-Front-End-Templates#766]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- it is website for buying NFT mostly 3d nft the screenshot represents it correctly

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb4PTZxC8MrZOLXCkZaAl7C80cUJbtOd6h7woc7FpYLAtMti6c)

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged add clear description.
