### ISSUE TITLE
Nav Bar Animated

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Cool-Front-End-Templates#768]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Animated NavBar

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![preview](https://user-images.githubusercontent.com/72241207/166906102-17e5e986-4805-4992-8b42-22c331b4cabf.gif)

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged open this issue in css project.
