### ISSUE TITLE
Can I add amazon slider

### ISSUE THREAD

**Issue by SamarthKadam** [arpit456jain/Cool-Front-End-Templates#786]
This is an Amazon slider that is fully responsive. Focused on sliding part on frontend technologies. You can look below in the video

https://user-images.githubusercontent.com/87573175/167435054-63917514-a914-44bf-8951-b41211f89a08.mp4

**Comment by DEEPIKA-SUK** [comment]
@SamarthKadam do it within 3 days.

**Comment by SamarthKadam** [comment]
Ohk
