### ISSUE TITLE
Cool letter animation website

### ISSUE THREAD

**Issue by TANYA-CHAN** [arpit456jain/Cool-Front-End-Templates#787]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

An interactive letter animation layout using HTML, CSS & JS.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
https://tanya-chan.github.io/letter-animation/

**Comment by TANYA-CHAN** [comment]
@astha2412 please check this out

**Comment by DEEPIKA-SUK** [comment]
@TANYA-CHAN do it within 3 days

**Comment by TANYA-CHAN** [comment]
okat tysm

**Comment by TANYA-CHAN** [comment]
do I have to put a  style_link.json file? I do not have spaces in my project. @DEEPIKA-SUK
