### ISSUE TITLE
Art Gallery Website

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#788]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Wan to add A website made using HTML, CSS and Javascript

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @astha2412 @DEEPALI-SUK Please assign the task

**Comment by DEEPIKA-SUK** [comment]
@Abh1shekSingh art gallery website template already exists.

**Comment by Abh1shekSingh** [comment]
Bro that is something else @DEEPIKA-SUK

**Comment by Abh1shekSingh** [comment]
![sa](https://user-images.githubusercontent.com/71981463/167565236-34c4da3f-ebf3-40b4-818f-ffc012fa91a8.JPG)
This is mine @DEEPIKA-SUK

**Comment by DEEPIKA-SUK** [comment]
@Abh1shekSingh do it within 2-3 days.
