### ISSUE TITLE
B: Design a website for a local Fast Food Shop

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#800]
Must include an image gallery and customer review section.

**Comment by shahnehal0407** [comment]
I would love to work on it. please assign it to me.

**Comment by DEEPIKA-SUK** [comment]
@shahnehal0407 do it within 3 days.

**Comment by shahnehal0407** [comment]
sure

**Comment by shahnehal0407** [comment]
> @shahnehal0407 do it within 3 days.

sure

**Comment by aachal28** [comment]
Kindly assign me this issue

**Comment by VidhiBhatt01** [comment]
@aachal28 we assign on FCFS basis

**Comment by SAMRIDHISINHA** [comment]
Please assign this issue to me.
