### ISSUE TITLE
C: Design a website for a company selling dairy products

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#801]
Must include a customer review and contact us page

**Comment by SamarthKadam** [comment]
Can I work on this ?

**Comment by SamarthKadam** [comment]
Can You please elaborate how should the project be?

**Comment by DEEPIKA-SUK** [comment]
@SamarthKadam finish it within 3 days.

**Comment by SamarthKadam** [comment]
So Im done with home page 
![Screenshot (195)](https://user-images.githubusercontent.com/87573175/169339469-6f43a1df-eeac-4edd-876b-926e742c492a.png)
So I am supposed to add customer review and contacts

**Comment by VidhiBhatt01** [comment]
Yes, that's the minimum

**Comment by VidhiBhatt01** [comment]
The home page looks cool btw
