### ISSUE TITLE
D: Design a website for a Cake Shop

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#802]
Must include an Image gallery and customer review page

**Comment by coolblizzarts** [comment]
Hello Payal here, I would like to contribute to this issue. Can you please assign it to me. Regards.

**Comment by DEEPIKA-SUK** [comment]
@coolblizzarts do it within 3 days.

**Comment by DEEPIKA-SUK** [comment]
@coolblizzarts any updates?

**Comment by coolblizzarts** [comment]
> @coolblizzarts any updates?

Hello, I have completed the task. Can you please check I have generated a  PR for the same.

**Comment by arpit456jain** [comment]
@coolblizzarts  which PR ?
link the PR to issue

**Comment by coolblizzarts** [comment]
> @coolblizzarts which PR ? link the PR to issue

https://github.com/arpit456jain/Cool-Front-End-Templates/pull/840#pullrequestreview-980895403

**Comment by coolblizzarts** [comment]
https://github.com/arpit456jain/Cool-Front-End-Templates/pull/887

I have created a new PR with the changes requested. Kindly provide feedback.
