### ISSUE TITLE
E: Design a website showing information about various festivals celebrated in India

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#803]
Make this website by adding cards for the festivals

**Comment by AyushJ16** [comment]
I would like to work on this!
I will generate PR as soon as possible.
Please assign me this issue!

**Comment by coolblizzarts** [comment]
Hello Payal here, I would like to contribute to this issue. Can you please assign it to me. Regards.

**Comment by aachal28** [comment]
Kindly assign me this issue
