### ISSUE TITLE
F: Design a website for a car manufacturing company named Betta

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#804]
Must include some basic information about cars and the features

**Comment by srinjoy-26** [comment]
Assign me @VidhiBhatt01 , I would like to work on this

**Comment by DEEPIKA-SUK** [comment]
@srinjoy-26 make the pr by tomorrow.

**Comment by srinjoy-26** [comment]
> @srinjoy-26 make the pr by tomorrow.

My exams are on , I would surely make a PR on Saturday

**Comment by DEEPIKA-SUK** [comment]
@srinjoy-26 make the PR by today.
