### ISSUE TITLE
G: Design a website that gives information about the breeds of dogs and cats

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#805]
Make this website by adding cards.

Website flow:
1. Display a welcome message and give two buttons asking the user to pick between a cat and a dog.
2. Redirect the user to the required page and display information.
3. You can also add a search bar on the top of both these pages.

**Comment by coolblizzarts** [comment]
Hello Payal here, I would like to contribute to this issue. Can you please assign it to me. Regards.

**Comment by aachal28** [comment]
Kindly assign me this issue

**Comment by DEEPIKA-SUK** [comment]
@coolblizzarts any updates?

**Comment by DEEPIKA-SUK** [comment]
@coolblizzarts make the PR by today.

**Comment by coolblizzarts** [comment]
> @coolblizzarts make the PR by today.

Hi, could you please give me 2 more days. My exams were going on so couldn't make the PR. Apologies.

**Comment by DEEPIKA-SUK** [comment]
@coolblizzarts okay do asap bcoz after 25th no PR will be reviewed.

**Comment by arpit456jain** [comment]
@aachal28 r u interested ?

**Comment by aachal28** [comment]
@arpit456jain yeah i love to work on this

**Comment by astha2412** [comment]
@aachal28 Make PR Tomorrow!
