### ISSUE TITLE
H: Design a website for a sports academy

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Cool-Front-End-Templates#806]
Must include services provided and achievements page

**Comment by aachal28** [comment]
Kindly assign me this issue

**Comment by DEEPIKA-SUK** [comment]
@aachal28 finish it within 3 days.

**Comment by aachal28** [comment]
Yeah sure I'll try my best

**Comment by aachal28** [comment]
Hey I'm working on this issue please give me more time.

**Comment by DEEPIKA-SUK** [comment]
@aachal28 make the PR by tomorrow.

**Comment by astha2412** [comment]
@aachal28 ???? Complete it asap otherwise, I will close this issue!
