### ISSUE TITLE
want to make a mobile template 

### ISSUE THREAD

**Issue by Yashashviarora** [arpit456jain/Cool-Front-End-Templates#826]
i want to make a template of mobile using html css and javascript.  please assign me

**Comment by DEEPIKA-SUK** [comment]
@Yashashviarora elaborate your issue.

**Comment by Yashashviarora** [comment]
like in this i make a nav bar and after below it there is a slider in which there are a lot of mobile to see and there is also a link on clicking that link customer can directly visit on amazon or any other web where he/she can order mobile of that model.

**Comment by DEEPIKA-SUK** [comment]
@Yashashviarora finish it within 3 days.

**Comment by DEEPIKA-SUK** [comment]
@Yashashviarora Make the PR by tomorrow otherwise we will close this issue.

**Comment by Yashashviarora** [comment]
ok i will di it tommorrow in any way

**Comment by Yashashviarora** [comment]
But when you assign you gave me 12 days

**Comment by DEEPIKA-SUK** [comment]
> But when you assign you gave me 12 days

Nobody gave you 12 days.

**Comment by Yashashviarora** [comment]
okk i will make pr tomorrow for sure

**Comment by Yashashviarora** [comment]
Plz don’t close it I make a responsive so give me only 5 min I make pr

**Comment by Yashashviarora** [comment]
I am unable to make pr because of error (updates were rejected) can you please explain me how to make pr now
