### ISSUE TITLE
Want to Improve Pizza Corner Project

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Cool-Front-End-Templates#833]
## Issue Type:

- [x] Bug Report
- [x] Feature Request

## **Describe the bug**

- Will Improve the UI of Pizza Corner UI.

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @astha2412 @DEEPIKA-SUK Please Assign the task to me

**Comment by DEEPIKA-SUK** [comment]
One issue will be assigned at one time.

**Comment by Abh1shekSingh** [comment]
@DEEPIKA-SUK  @VidhiBhatt01  please assign this One first before my other issues

**Comment by VidhiBhatt01** [comment]
Any updates?

**Comment by Abh1shekSingh** [comment]
Yes, I am doing.

**Comment by DEEPIKA-SUK** [comment]
@Abh1shekSingh make the PR y tomorrow otherwise we will close this issue.

**Comment by Abh1shekSingh** [comment]
Exam are on. But I will Manage somehow

**Comment by DEEPIKA-SUK** [comment]
@Abh1shekSingh try to finish it by 24th bcoz after 25th no PR will be reviewed.
