### ISSUE TITLE
Responsive Sign-In Form with appealing styling.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [arpit456jain/Cool-Front-End-Templates#835]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **Describe the bug**

I have noticed that there is no Sign-In form template available on your website with good modern styling.

## **Possible solution**

I want to add a CSS template for a modern Sign-In Form. I am a GSSOC'22 participant, kindly assign this issue to me. Thank you!

## **Screenshots**

No screenshots are available.

**Comment by DEEPIKA-SUK** [comment]
Sign In form template already exists.

**Comment by KiranAminPanjwani** [comment]
Okay, no issues.
