### ISSUE TITLE
Would like to add About Us page

### ISSUE THREAD

**Issue by Siddhi-Mundada** [arpit456jain/Cool-Front-End-Templates#838]
Feature Request
I would like to add About Us page in this website with animation.  Image of Project Admin , information about the website and Some links.
Please assign this issue to me under GSSOC 22.
Thanks in Advance.

**Comment by VidhiBhatt01** [comment]
Sorry, but the PA has given us the orders of not to assign any issues related to the changes in main website. You can check out other existing issues : )
