### ISSUE TITLE
Improve Website 

### ISSUE THREAD

**Issue by hariketsheth** [arpit456jain/Cool-Front-End-Templates#841]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**
- Images are unavailable for a lot of projects.
- Would like to solve this issue so that frontend of the website doesn't get disturbed

@DEEPIKA-SUK, Please assign

**Comment by DEEPIKA-SUK** [comment]
@hariketsheth complete it by 22th may

**Comment by DEEPIKA-SUK** [comment]
@hariketsheth complete it by 21st may
