### ISSUE TITLE
Want to add a minion translator app template

### ISSUE THREAD

**Issue by Mohasin-Haque** [arpit456jain/Cool-Front-End-Templates#842]
## Issue Type:

- [x] Feature Request

## **Possible solution**

I visited the repo and does not found any translator app template. I would love to contribute some translator app template. These templates are fun to use.

## **Screenshots**

- Here are some of the preview of the template. 

1. Banana Translator
![Banana Translator](https://user-images.githubusercontent.com/72180173/169211704-a7d8d1be-c966-4e6e-9cac-dc0dc6dbbeb6.png)

2. Morse Code Translator
![Morse Code Translator](https://user-images.githubusercontent.com/72180173/169211844-d4fd6a7f-ae00-4b57-9b02-ba4bf0fb14fb.png)

3. Pirates Translator
![Pirates Translator](https://user-images.githubusercontent.com/72180173/169212119-f65f0721-ba7d-4362-95f0-2b3f23de2e6d.png)

**Comment by DEEPIKA-SUK** [comment]
@Mohasin-Haque finish it by 21th may.

**Comment by DEEPIKA-SUK** [comment]
@Mohasin-Haque finish it by 21st may.

**Comment by Mohasin-Haque** [comment]
@DEEPIKA-SUK I have added the first template i.e. Banana Translate. How can I add the next two templates?

**Comment by DEEPIKA-SUK** [comment]
> @DEEPIKA-SUK I have added the first template i.e. Banana Translate. How can I add the next two templates?

It would be good if you create one html page which has links for all three translator html pages instead of creating three different projects for the translator.
