### ISSUE TITLE
Catering Website

### ISSUE THREAD

**Issue by DhairyaWankhade** [arpit456jain/Cool-Front-End-Templates#845]
- [ ] Feature Request

Want to add a good template for catering website.

**Comment by DEEPIKA-SUK** [comment]
One issue at a time will be assigned. You can open this issue again once you complete previous issue.

**Comment by DhairyaWankhade** [comment]
> One issue at a time will be assigned. You can open this issue again once you complete previous issue.

I have completed & submitted the earlier issue. Can u please assign me this issue now..
