### ISSUE TITLE
Search Github Profiles from a website

### ISSUE THREAD

**Issue by praniti111** [arpit456jain/Cool-Front-End-Templates#846]
Hey There!
I wanted to make a template for websites that can search the Github Profiles without opening Github.
The template will contain

Profile Picture
Name
Number of followers and following
Description of the user.
I am a GSSoC22 participant, and would like to work on this project!
- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DEEPIKA-SUK** [comment]
@praniti111 create a new PR. Earlier one won't be considered.

**Comment by praniti111** [comment]
Thank you @DEEPIKA-SUK
