### ISSUE TITLE
Floor plan Website

### ISSUE THREAD

**Issue by Kamleshseervi** [arpit456jain/Cool-Front-End-Templates#850]
I want to create a website which contains different floor plans according to  length and breadth of floor

**Comment by VidhiBhatt01** [comment]
Can you add some SS or video?

**Comment by VidhiBhatt01** [comment]
Also, if you are using JS for this I would suggest you to close the issue here and raise it Amazing JS projects repo

**Comment by astha2412** [comment]
@Kamleshseervi ????

**Comment by Kamleshseervi** [comment]
I will use html css more so i want to raise pr here

**Comment by DEEPIKA-SUK** [comment]
@Kamleshseervi finish it within 2 days.

**Comment by Kamleshseervi** [comment]
Please give me a week because i am stuck in college exam

**Comment by DEEPIKA-SUK** [comment]
@Kamleshseervi after 25th no PR will be reviewed. GSSoC is ending on 31st May so after that no PRs would be considered under GSSoC.

**Comment by Kamleshseervi** [comment]
I will try to submit on or before 25
