### ISSUE TITLE
Adding  Banking Website

### ISSUE THREAD

**Issue by SamarthKadam** [arpit456jain/Cool-Front-End-Templates#851]
This is the website Where you can see multiple functionalities. This website is built using Javascript and frontend technologies.
This project was built under guidance of the instructor
The functionality you see here is
1>Sticky navigation on specified view
2>When viewing one of the links other links become blurred
3>Lazy loading images
4>Tabbed component
5>Slider

Below is just starting page. There are many pages
![Screenshot (169)](https://user-images.githubusercontent.com/87573175/169355374-fdfe308b-87a2-4c92-9971-893082074c4a.png)

**Comment by SamarthKadam** [comment]
Can i add this?

**Comment by astha2412** [comment]
Complete it within 2 days and Make PR ASAP!
