### ISSUE TITLE
Adding a Headphone Landing Page

### ISSUE THREAD

**Issue by itzwow** [arpit456jain/Cool-Front-End-Templates#861]
## Issue Type:

- [ x] Feature Request

## **Describe the bug**

Want to add a new responsive Headphone Landing page template 

## **Screenshots**

![f1](https://user-images.githubusercontent.com/84179065/169596391-f9f6a6b6-a4db-4e5e-9c7d-d13b3aea10a7.JPG)

I'm a GsSOC'22 participant and wanted to contribute in it

**Comment by astha2412** [comment]
@itzwow Complete it within 2 days and Make PR ASAP!
