### ISSUE TITLE
Adding Model Window

### ISSUE THREAD

**Issue by SamarthKadam** [arpit456jain/Cool-Front-End-Templates#863]
This is a Small Template of the Model window when the user clicks some link a model window is brought into the screen.And its background is blured. Below you can have a look. Can I add this?

![Screenshot (197)](https://user-images.githubusercontent.com/87573175/169655354-0751abfb-7e7e-4240-9a55-288ef721c2fe.png)

**Comment by astha2412** [comment]
@SamarthKadam Complete it within 2 days and make PR ASAP!
