### ISSUE TITLE
Design a website for selling flowers

### ISSUE THREAD

**Issue by SAMRIDHISINHA** [arpit456jain/Cool-Front-End-Templates#864]
Hello, I am Samridhi(GGSOC'22 contributor) and I want to bulid the website for selling flowers

**Comment by astha2412** [comment]
@SAMRIDHISINHA Complete it within 2 days......and make PR Asap!! Attach ss also.

**Comment by SAMRIDHISINHA** [comment]
Okay,sure

**Comment by SAMRIDHISINHA** [comment]
I was making the pr, what happened?

**Comment by astha2412** [comment]
@SAMRIDHISINHA Make PR Asap, as we have very less time to check all your issues and PRs.
