### ISSUE TITLE
Candy Museum

### ISSUE THREAD

**Issue by tarunbisht-24** [arpit456jain/Cool-Front-End-Templates#865]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

Hey, Project admin I'm a GSSOC participant and I want to add a Responsive Candy Museum page 

## **Possible solution**

- Describe the solution you thought of.

I will create the page with HTML CSS Bootstrap and a little bit of JS it is an excellent practice to create a landing page for beginners. It will be mobile responsive too. Please go through the issue and assign me this issue to work on.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

It will look like this

<img width="960" alt="preview1" src="https://user-images.githubusercontent.com/77788209/169664125-40f5e63d-8c3b-46af-96f4-c4ea0ae24963.png">
<img width="378" alt="preview2" src="https://user-images.githubusercontent.com/77788209/169664137-52c4a2e9-281f-4ed9-a8de-235f9036ea94.png">

**Comment by astha2412** [comment]
@tarunbisht-24 complete it within 2 days
