### ISSUE TITLE
Bug in Readme.md

### ISSUE THREAD

**Issue by itzwow** [arpit456jain/Cool-Front-End-Templates#867]
## Issue Type:

- [ x] Documentaion

## **Describe the bug**

- Typo in git clone command under Clone and Forked repository in README.md file

## **Possible solution**

- correct URL for clone command

## **Screenshots**

![issue1](https://user-images.githubusercontent.com/84179065/169667445-6e4fb904-0db8-493a-a913-7e3befcc2efd.JPG)

I want to work on it. Kindly assign it to me. 
I am a GsSOC'22 participant

**Comment by DEEPIKA-SUK** [comment]
@itzwow finish it by today itself.
