### ISSUE TITLE
Responsive SAAS product landing page

### ISSUE THREAD

**Issue by prabhkaur301** [arpit456jain/Cool-Front-End-Templates#871]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

Responsive landing page with sign up form with validation.

![image](https://user-images.githubusercontent.com/57444962/169687594-0c8369d2-6cab-49ab-ba02-5fcb48eb509a.png)

Kindly assign me this issue

**Comment by DEEPIKA-SUK** [comment]
@prabhkaur301 finish it within 2 days itself. No more extra time will be given.
