### ISSUE TITLE
Animaton Template

### ISSUE THREAD

**Issue by SamarthKadam** [arpit456jain/Cool-Front-End-Templates#872]
This is an Animation Template built using css and html you can see its preview below

https://user-images.githubusercontent.com/87573175/169688146-3bd39868-fc7e-4598-9948-9abc12d8fc2a.mp4

**Comment by SamarthKadam** [comment]
Can I add this?

**Comment by DEEPIKA-SUK** [comment]
@SamarthKadam open this in Amazing CSS or Amazing JS (if javascript is used) repo.
