### ISSUE TITLE
Adding Hover Animation Bar

### ISSUE THREAD

**Issue by SamarthKadam** [arpit456jain/Cool-Front-End-Templates#886]
Can I add this project which is completely ready and I'll make sure to make pr by tomorrow morning . Please assign this to me . I'll make the pr very fast below you can see the project preview

https://user-images.githubusercontent.com/87573175/170090409-c35cb9d8-a90c-4bee-be3e-36865dd6c413.mp4

**Comment by SamarthKadam** [comment]
@VidhiBhatt01  I'll make pr by tomorrow morning. Why guys are you not taking any issues as we have got 6 days remaining for coding period to end . So please consider this issue. I'll make this pretty fast

**Comment by VidhiBhatt01** [comment]
We need to sort the repos and identify plag content too, and it's time consuming. Assigning you still, but make sure you complete it before tomorrow 12pm

**Comment by SamarthKadam** [comment]
@VidhiBhatt01 thank you and yes I'll complete it by today only
