### ISSUE TITLE
Delete expired templates.

### ISSUE THREAD

**Issue by Kotak-Prerit** [arpit456jain/Cool-Front-End-Templates#907]
There are lots of expired templets that are still available on the site. 

![error404](https://user-images.githubusercontent.com/97387752/193621426-1e086404-f374-4f76-bdc2-0c70baf46563.png)

**Comment by arpit456jain** [comment]
go ahead @Kotak-Prerit

**Comment by Kotak-Prerit** [comment]
On it. 👍🏼

**Comment by Kotak-Prerit** [comment]
Bro there are also 7 templates who are added twice. So can I delete the 2nd
copy?

**Comment by arpit456jain** [comment]
yes

**Comment by Kotak-Prerit** [comment]
Hey there! I've sent a merge request do check it out & accept if everything
is okay.
