### ISSUE TITLE
Links broken of some webapps

### ISSUE THREAD

**Issue by heyvats21** [arpit456jain/Cool-Front-End-Templates#912]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request

## **Describe the bug**

- if we click on the view part so it redirects to the wrong web page

## **Screenshots**

![image](https://user-images.githubusercontent.com/81029204/194741749-dbb800e2-d431-4dd6-955d-fc8717cf3467.png)

assign me under hacktoberfest .

**Comment by heyvats21** [comment]
can i start contributing?

**Comment by arpit456jain** [comment]
yes

**Comment by cybraia** [comment]
hi, is the issue resolved? Could you assign it to me, if not?

**Comment by thesri** [comment]
hey are these issues resolved? could you assign it to me, if not ?
