### ISSUE TITLE
[BUG] : Move to top icon should be placed correctly

### ISSUE THREAD

**Issue by subrat611** [arpit456jain/Cool-Front-End-Templates#922]
Hey @arpit456jain I want to fix this minor issue. Could you assign this to me?

## **Screenshots**
![image](https://github.com/arpit456jain/Cool-Front-End-Templates/assets/77252075/373b9bfe-2fa0-4a02-8712-0aefc66221fd)

**Comment by arpit456jain** [comment]
@subrat611 make a fresh PR and try to write clean code with comments
