### ISSUE TITLE
Removing pizza corner as it already exists with another name

### ISSUE THREAD

**Issue by deveshidwivedi** [arpit456jain/Cool-Front-End-Templates#923]
## Issue Type:

- [✅ ] Bug Report
- [  ] Feature Request
- [ ] Documentaion

## **Describe the bug**
There exist two Pizza Corner templates named as "Pizza Corner" and "Pizza Corner New Design". No images are displayed in the former and it looks incomplete and the same font and similar color scheme is used in the later. So, "pizza corner" could be removed.
- 

## **Possible solution**

- Pizza Corner could be removed from the website as the other design follows similar scheme and design, or it could be changed completely to give users an option to choose from the two pizza corner templates.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

<img width="924" alt="1" src="https://github.com/arpit456jain/Cool-Front-End-Templates/assets/120312681/bc7ae04c-273b-43a8-8441-0220a0cb2d0e">
<img width="916" alt="2" src="https://github.com/arpit456jain/Cool-Front-End-Templates/assets/120312681/15cfc1cc-2d06-4dc3-be49-eb2b13821921">
<img width="913" alt="3" src="https://github.com/arpit456jain/Cool-Front-End-Templates/assets/120312681/772d4360-2d8b-4702-9a3b-a084a009c548">
<img width="932" alt="4" src="https://github.com/arpit456jain/Cool-Front-End-Templates/assets/120312681/323b7425-9c9d-4ddb-82ae-7f8906d2ea98">

**Comment by juperameza** [comment]
Hi, is the issue being work on ? 
I'll be happy to work on it but I think the best solution is to keep both templates and fix the old one instead of deleting it .But let me know what you think

**Comment by arpit456jain** [comment]
@deveshidwivedi go ahead

**Comment by Raj100** [comment]
please assign I will work on it
