### ISSUE TITLE
[Bug]: Blank space visible at the bottom of the page

### ISSUE THREAD

**Issue by subrat611** [arpit456jain/Cool-Front-End-Templates#926]
## Issue Type:

- [X] Bug Report

## **Describe the bug**

- A huge amount of blank space is visible bottom of the page.

## **Possible solution**

- Remove the extra spaces.

## **Screenshots**
![image](https://github.com/arpit456jain/Cool-Front-End-Templates/assets/77252075/febca58d-af17-43cb-9911-1f41ff0f1ef3)

**Comment by subrat611** [comment]
Hey @arpit456jain I want to fix this minor issue. Could you assign this to me?

**Comment by Raj100** [comment]
i will do it

**Comment by arpit456jain** [comment]
not required
